### PR TITLE
bug 6448: Do not use wxWidget env-variable expand flag when adding to `audacityPathList`

### LINKED ISSUE #6448: Audacity fails to find modules when installed in a directory with a dollar sign in its path
### Bug description

_No response_

### Steps to reproduce

1. install Audacity to a non-default path containing a dollar sign (e.g. `D:\$Root\$Apps\Audacity\3.5.1\Audacity.exe`)
2. run Audacity
3. check Preferences > Modules

### Expected behavior

All modules show up

### Actual behavior

No modules are discovered by Audacity

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #6448 

`wxFileName::Normalize()` by default uses (among others) the `wxPATH_NORM_ENV_VARS`.
On Windows, this environment-variable path expansion option has a [bug](https://github.com/wxWidgets/wxWidgets/issues/19214), causing #6448. (Note that the way this was resolved by wxWidgets was by discouraging the use of that option, rather than fixing the problem itself.)

We are using `Normalize` as Audacity collects paths where to look for modules. Looking at the code ending at the place where we make this call to `Normalize`, it seems to me that environment variable expansion is not needed, and can hence be disabled (see diff).

We make other calls to `Normalize` in other contexts, which I reviewed. There seems not to be a need to disable this option there, but I would like to have the opinions of the reviewers.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by LWinterberg — APPROVED** [review]

File: libraries/lib-files/FileNames.cpp [hunk 1]
```diff
@@ -626,7 +626,12 @@ void FileNames::AddUniquePathToPathList(const FilePath &pathArg,
                                           FilePaths &pathList)
 {
    wxFileNameWrapper pathNorm { pathArg };
-   pathNorm.Normalize();
+   // https://github.com/audacity/audacity/issues/6448 :
+   // Do not seek to expand environment variables here: it is not needed, and
+   // wxWidgets has an issue doing so - See
+   // https://github.com/wxWidgets/wxWidgets/issues/19214
+   const auto flags = wxPATH_NORM_ALL & ~wxPATH_NORM_ENV_VARS;
```
Comment (vsverchinsky) [inline libraries/lib-files/FileNames.cpp:633]: One thing that bothers me a bit is that `AddUniquePathToPathList` isn't unique anymore

**Review by vsverchinsky — APPROVED** [review]

File: libraries/lib-files/FileNames.cpp (hunk 1 above)
Comment (saintmatthieu) [reply libraries/lib-files/FileNames.cpp:633]: You mean it was unique before this change and now it isn't ? I don't understand.

**Comment by saintmatthieu** [comment]
@LWinterberg @vsverchinsky the first commit fixed the scanning of the module paths, but not the readout from `audacity.cfg`, which had the same problem again. The second commit should address that.

File: libraries/lib-files/FileNames.cpp (hunk 1 above)
Comment (vsverchinsky) [reply libraries/lib-files/FileNames.cpp:633]: No, I just didn't think well enough about it, please ignore that comment

**Review by LWinterberg — APPROVED** [review]

**Review by vsverchinsky — APPROVED** [review]
