### PR TITLE
9435 Update meters at a fixed rate despite portaudio

### LINKED ISSUE #9435: Update meters at a fixed rate
### Description

The meter is updated every time `audacityAudioCallback` is called.
The problem is we open the stream with `paFramesPerBufferUnspecified` parameters. The number of frames and the rate at which the meter is updated can vary significantly.
This can be easily verified by enabling audio input monitoring.

### PR DESCRIPTION
**Pull request by embarc-gabriel**
Resolves: #9435 

Make the meter update rate independent from portaudio callback execution rate.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:

- [ ] Autobot test cases have been run

### CODE REVIEW

File: src/au3wrap/internal/au3audiometer.cpp [hunk 1]
```diff
@@ -26,18 +31,39 @@ IMeterSender::Sample GetAbsValue(const float* buffer, size_t frames, size_t step
...
+    }
+
+    const auto value = getSamplesMaxValue(sampleData.buffer, sampleData.frames, sampleData.nChannels);
+    if (value.peak > m_maxValue[channel].peak) {
+        m_maxValue[channel] = value;
+    }
+
+    const double lastSampleTimestamp = sampleData.firstSampleTimestamp + sampleData.frames * (1 / m_sampleRate);
+    if (lastSampleTimestamp > *m_lastSampleTimestamp[channel] + METER_SAMPLE_PERIOD) {
+        // Send data every METER_SAMPLE_PERIOD seconds approximately.
```
Comment (embarc-gabriel) [inline src/au3wrap/internal/au3audiometer.cpp:71]: @saintmatthieu I know it is not the same rate, but I think it is close enough. It isn't worth it to make it even closer if the user won't be able to perceive it in my opinion.

File: src/au3wrap/internal/au3audiometer.h [hunk 2]
```diff
@@ -31,7 +40,13 @@ class Meter : public IMeterSender, public muse::async::Asyncable
...
     };
 
+    Sample getSamplesMaxValue(const float* buffer, size_t frames, size_t step);
+    void push(uint8_t channel, const Sample& sample, int64_t key);
+
+    double m_sampleRate{ 44100.0 };
     std::vector<Data> m_trackData;
     std::map<int64_t, muse::async::Channel<au::audio::audioch_t, au::audio::MeterSignal> > m_channels;
+    std::map<int64_t, Sample> m_maxValue{};
+    std::map<int64_t, std::optional<double> > m_lastSampleTimestamp{};
```
Comment (saintmatthieu) [inline src/au3wrap/internal/au3audiometer.h]: It seems to me that the value type of this map could be just `double` ?

File: src/au3wrap/internal/au3audiometer.h [hunk 3]
```diff
@@ -10,19 +10,28 @@
...
+    void setSampleRate(double rate) override;
+
     muse::async::Channel<au::audio::audioch_t, au::audio::MeterSignal> dataChanged(int64_t key = MASTER_TRACK_ID);
 
 private:
+    struct Sample
+    {
+        float peak;
+        float rms;
+    };
```
Comment (saintmatthieu) [inline src/au3wrap/internal/au3audiometer.h:37]: Minor: why not defaulting these to 0.f? It'd make it safer and also you could use the default ctor in the source file.

**Review by saintmatthieu — APPROVED** [review]
