### PR TITLE
Use aligned vector in GetNormalizedCircularAutocorr, too.

### LINKED ISSUE #5906: Occasional crash in tempo estimation
### Bug description

Importing that audio file sometimes crashes Audacity: [AudacitySpectral.zip](https://github.com/audacity/audacity/files/14126902/AudacitySpectral.zip)

### Steps to reproduce

1. On empty project, import that file

### Expected behavior

File opens

### Actual behavior

Audacity crashes

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Crash occurs in PFFFT, when used by the recently introduced tempo-estimation algorithm.
Seems intermittent (??)

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #5906 

A use of PFFFT was forgotten in #5950

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: libraries/lib-music-information-retrieval/MirDsp.cpp [hunk 1]
```diff
@@ -84,14 +84,16 @@ std::vector<float> GetMovingAverage(const std::vector<float>& x, double hopRate)
 }
 } // namespace
 
-std::vector<float> GetNormalizedCircularAutocorr(std::vector<float> x)
+std::vector<float>
+GetNormalizedCircularAutocorr(std::vector<float> ux /* unaligned x*/)
```
Comment (crsib) [inline libraries/lib-music-information-retrieval/MirDsp.cpp:88]: I think, but I might be wrong, that const ref should be used now in this place. `x` is no longer used in place, and the ownership of `x` is not transferred on the main branch

**Review by crsib — APPROVED** [review]
I have just one, quite minor concern. It's not blocking for sure

**Comment by saintmatthieu** [comment]
> I have just one, quite minor concern. It's not blocking for sure

Addressed. Squashed and hard-pushed.
