### PR TITLE
Pitch shift display fixes

### LINKED ISSUE #6062: Pitch shifting by cents loses indicator
When pitch shifting a clip by, say, 2 semitones and 14 cents, the indicator disappears. Expected behavior would be to show "↑2.14"

### LINKED ISSUE #6092: Pitch indicator always shows decimal separator in non-period-for-decimal languages
image

Note the stray , in the UI

Steps to reproduce:

1. set language to german
2. change pitch on a clip

### LINKED ISSUE #6140: When a clip has a non-zero cents value, the pitch indicator is not displayed
### Steps to reproduce

1. Grab some audio clip
2. Right-click > Pitch and speed or Ctrl + Shift + P
3. Enter a non-zero "cents" value
4. Click OK to close the dialog
5. Review the clip's title bar

### Expected behavior

The pitch indicator is in the title bar.

### Actual behavior

The pitch indicator is displayed only when the cents value is zero.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #6062, #6092, #6140

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: src/tracks/playabletrack/wavetrack/ui/ClipPitchAndSpeedButtonHandle.cpp [hunk 1]
```diff
@@ -36,7 +36,7 @@ wxString GetPitchShiftText(int clipCentShift)
       pitchShiftText = wxString::Format("%.2f", std::abs(clipCentShift) / 100.);
       while (pitchShiftText.EndsWith("0"))
          pitchShiftText.RemoveLast();
-      if (pitchShiftText.EndsWith("."))
+      if (pitchShiftText.EndsWith(".") || pitchShiftText.EndsWith(","))
```
Comment (LWinterberg) [inline src/tracks/playabletrack/wavetrack/ui/ClipPitchAndSpeedButtonHandle.cpp:39]: perhaps a regex non-match for [0-9] would be more complete, but I can't actually find any language using something other than period or comma for a separator, so this probably works too.

**Review by LWinterberg — APPROVED** [review]
