### PR TITLE
fix erroneous not-enough-space error

### LINKED ISSUE #6004: Not enough space to change pitch
### Bug description

When attempting to change the **_pitch_** of a clip that has an adjacent clip on the  right, Audacity complains that there is not sufficient space.

### Steps to reproduce

1. Generate a 10 second, 440 Hz tone
2. Click somewhere near the middle
3. "Ctrl + I" (split)
4. Double click on the first clip to select it
5. Right click on the first clip
6. Select "Pitch and Speed..."
7. Optional: Change the "semi-tones" to a non-zero value (_Bug occurs even for zero change_)
8. Apply

### Expected behavior

The pitch of the selected clip to be changed by the specified amount.

### Actual behavior

Screenshot_2024-02-21_15-54-58

### Audacity Version

current master / alpha / nightly build

### Operating system

All

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #6004

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: src/tracks/playabletrack/wavetrack/ui/PitchAndSpeedDialog.cpp [hunk 1]
```diff
@@ -310,7 +310,7 @@ bool PitchAndSpeedDialog::SetClipSpeedFromDialog()
    const auto expectedEndTime =
       start + (end - start) * mOldClipSpeed / mClipSpeed;
 
-   if (expectedEndTime >= maxEndTime)
+   if (expectedEndTime > maxEndTime)
```
Comment (saintmatthieu) [inline src/tracks/playabletrack/wavetrack/ui/PitchAndSpeedDialog.cpp:313]: `maxEndTime` is the start time of the next clip, and `expectedEndTime`, that of this clip after stretch. It's fine for them to be equal: clip boundaries abide by a closed-begin/open-end rule.

**Review by crsib — APPROVED** [review]
