### PR TITLE
6505 fix graph delay when using lookahead

### LINKED ISSUE #6505: Limiter graph: adding look-ahead delays the graph
### Bug description

_No response_

### Steps to reproduce

1. Create a track with some audio
2. Add real-time limiter (or compressor)
3. Open limiter editor
4. Enable "Show graph" option
5. Set lookahead to maximum
6. Press play

### Expected behavior

Graph is synchronized with playback

### Actual behavior

Graph is noticeably delayed, likely by the amount of look-ahead specified.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #6505

In addition to fixing the delay issue, this PR also modifies the aspect of the graph, using one line for the actual compression and a filled area to denote the difference between target and actual compression.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: src/effects/DynamicRangeProcessorHistoryPanel.cpp [hunk 1]
```diff
@@ -224,8 +225,10 @@ void DynamicRangeProcessorHistoryPanel::OnTimer(wxTimerEvent& evt)
    // because this can be triggered even when playback is paused.
    const auto now = std::chrono::steady_clock::now();
    if (!mSync)
-      mSync.emplace(ClockSynchronization {
-         mHistory->GetSegments().front().front().time, now });
+      mSync.emplace(
+         ClockSynchronization { mHistory->GetSegments().front().front().time +
+                                   mCompressorInstance.GetLatencyMs() / 1000,
```
Comment (vsverchinsky) [inline src/effects/DynamicRangeProcessorHistoryPanel.cpp:241]: What if lookahead has changedDo you need to `mSync.reset()` somewhere?

File: src/effects/DynamicRangeProcessorHistoryPanel.cpp [hunk 2]
```diff
@@ -92,19 +92,18 @@ constexpr auto followLineWidth =
...
    // A display delay to avoid the display to tremble near time zero because the
    // data hasn't arrived yet.
    // This is a trade-off between visual comfort and timely update. It was set
    // empirically, but with a relatively large audio playback delay. Maybe it
    // will be found to lag on lower-latency playbacks. Best would probably be to
    // make it playback-delay dependent.
    constexpr auto displayDelay = 0.2f;
-   return panelWidth - 1 -
-          std::round((elapsedSincePacket - 0.2f) / secondsPerPixel);
+   return panelWidth - 1 - (elapsedSincePacket - 0.2f) / secondsPerPixel;
```
Comment (vsverchinsky) [inline src/effects/DynamicRangeProcessorHistoryPanel.cpp:106]: `(elapsedSincePacket - displayDelay)`? Otherwise `displayDelay` is not used

File: src/effects/DynamicRangeProcessorHistoryPanel.cpp [hunk 3]
```diff
@@ -140,27 +144,38 @@ void DrawHistory(
          targetPoints.emplace_back(x, yt);
       }
 
-      gc.SetPen(wxPen { theTheme.Colour(clrResponseLines), followLineWidth });
-      if (segment.size() == 1)
+      // Draw the follow line in black, solid line ...
+      gc->SetPen(wxPen { wxColour { 0, 0, 0 } });
```
Comment (vsverchinsky) [inline src/effects/DynamicRangeProcessorHistoryPanel.cpp:148]: wxWidgets defines set of pen/brush constants. 
Could be replaced with `*wxBLACK_PEN`

File: src/effects/DynamicRangeProcessorHistoryPanel.cpp (hunk 1 above)
Comment (saintmatthieu) [reply src/effects/DynamicRangeProcessorHistoryPanel.cpp:241]: Our playback currently doesn't handle varying latency, see https://github.com/audacity/audacity/issues/3223. Will add a comment.

**Review by vsverchinsky — APPROVED** [review]
