### PR TITLE
fix(timeline): during playback seek and play

### LINKED ISSUE #9752: Clicking into the timeline during playback doesn't cause the playhead to move
1. Start playback
2. Click into the timeline to move the playhead
3. Observe: playhead won't move

### PR DESCRIPTION
**Pull request by embarc-gabriel**
Resolves: #9752 https://github.com/audacity/audacity/issues/9415

During playback seekToX should trigger play so we change the modify the position on clicking the timeline.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:

- [ ] Autobot test cases have been run

### CODE REVIEW

**Review by grliszas14 — APPROVED** [review]

**Comment by luapmartin** [comment]
let me suggest this enum renaming `State` as `ProcessingState`

```cpp

//! Sits in a thread loop reading and writing audio.
void AudioIO::AudioThread(std::atomic<bool>& finish)
{
    enum class ProcessingState {
        eSkipProcessing, ePrimeProcessing, eCallbackProcessing
    } lastState = ProcessingState::eSkipProcessing;
    AudioIO* const gAudioIO = AudioIO::Get();
    while (!finish.load(std::memory_order_acquire)) {
        using Clock = std::chrono::steady_clock;
        auto loopPassStart = Clock::now();
        auto& schedule = gAudioIO->mPlaybackSchedule;
        const auto interval = schedule.GetPolicy().SleepInterval(schedule);

        // Set LoopActive outside the tests to avoid race condition
        gAudioIO->mAudioThreadSequenceBufferExchangeLoopActive
        .store(true, std::memory_order_relaxed);
        if (gAudioIO->mAudioThreadShouldCallSequenceBufferExchangeOnce
            .load(std::memory_order_acquire)) {
            gAudioIO->SequenceBufferExchange();
            gAudioIO->mAudioThreadShouldCallSequenceBufferExchangeOnce
            .store(false, std::memory_order_release);

            lastState = ProcessingState::ePrimeProcessing;
        }
        else if (gAudioIO->mAudioThreadSequenceBufferExchangeLoopRunning
                   .load(std::memory_order_relaxed)) {
            if (lastState != ProcessingState::eCallbackProcessing) {
                // Main thread has told us to start - acknowledge that we do
                gAudioIO->mAudioThreadAcknowledge.store(Acknowledge::eStart,
                                                        std::memory_order::memory_order_release);
            }
            lastState = ProcessingState::eCallbackProcessing;

            // We call the processing after raising the acknowledge flag, because the main thread
            // only needs to know that the message was seen.
            //
            // This is unlike the case with mAudioThreadShouldCallSequenceBufferExchangeOnce where the
            // store really means that the one-time exchange was done.

            gAudioIO->SequenceBufferExchange();
        }
        else {
            if ((lastState == ProcessingState::eCallbackProcessing)
                || (lastState == ProcessingState::ePrimeProcessing)) {
                // Main thread has told us to stop; (actually: to neither process "once" nor "loop running")
                // acknowledge that we received the order and that no more processing will be done.
                gAudioIO->mAudioThreadAcknowledge.store(Acknowledge::eStop,
                                                        std::memory_order::memory_order_release);
            }
            lastState = ProcessingState::eSkipProcessing;
        }

        gAudioIO->mAudioThreadSequenceBufferExchangeLoopActive
        .store(false, std::memory_order_relaxed);

        std::this_thread::sleep_until(loopPassStart + interval);
    }
}
```

File: src/playback/internal/playbackcontroller.cpp [hunk 1]
```diff
@@ -391,7 +391,10 @@ void PlaybackController::onSeekAction(const muse::actions::ActionQuery& q)
     const muse::secs_t secs = q.param("seekTime").toDouble();
     const bool triggerPlay = q.param("triggerPlay").toBool();
 
-    if (isPaused()) {
+    const auto playbackRegion = player()->playbackRegion();
+    const bool isSeekStartPositionValid = playbackRegion.isValid() ? (secs <= playbackRegion.end) : (secs <= totalPlayTime());
+
```
Comment (luapmartin) [inline src/playback/internal/playbackcontroller.cpp]:
```cpp
    const bool isSeekStartPositionValid = isSeekPositionValid(secs);
```
something like this
```cpp
bool isSeekPositionValid(const muse::secs_t seekTimeToCheck)
{
    const auto playbackRegion = player()->playbackRegion();
return playbackRegion.isValid() ? (seekTimeToCheck <= playbackRegion.end) : (seekTimeToCheck <= totalPlayTime());
}
```

**Review by luapmartin — APPROVED** [review]

**Review by saintmatthieu — APPROVED** [review]
