### PR TITLE
9755 realtime effects no persistent fix

### LINKED ISSUE #9755: An effect added to the stack doesn't appear to stick
### Bug description

Effects added to the stack are lost when the project is closed and reopened.

### Steps to reproduce

1. New project
2. Add a new track
3. Add an effect to the stack
4. Close and save
5. Reopen the project
6. Open the track's effect stack
7. Look for the effect in the stack

### Expected behavior

The effect is present in the track's effect stack.

### Actual behavior

No effect in the track's effect stack. Restarting Audacity and reopening this project will fix the issue.

https://github.com/user-attachments/assets/36403bf6-3b73-4708-ad3f-b2b7084a1414

### Audacity Version

master

### Operating system

OS independent

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #9755

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:

- [ ] Autobot test cases have been run

### CODE REVIEW

File: src/projectscene/view/trackspanel/realtimeeffectlistmodel.cpp [hunk 1]
```diff
@@ -25,6 +25,13 @@ void RealtimeEffectListModel::onProjectChanged()
                 emit trackNameChanged();
             }
         });
+        const std::vector<au::trackedit::TrackId> trackIds = project->trackIdList();
+        for (const auto& trackId : trackIds) {
+            if (belongsWithMe(trackId)) {
+                // Project was just opened, we can use brute-force `onChanged`, it won't have an impact on scrollbar position or alike.
+                onChanged(trackId);
+            }
+        }
```
Comment (luapmartin) [inline src/projectscene/view/trackspanel/realtimeeffectlistmodel.cpp:34]: this does an "init()" kind of setup right ?

it's because we have "updates()" working and we want to have the "updates()" forced

Comment (saintmatthieu) [reply src/projectscene/view/trackspanel/realtimeeffectlistmodel.cpp:34]: Sorry, I don't understand the rationale.

Comment (luapmartin) [reply src/projectscene/view/trackspanel/realtimeeffectlistmodel.cpp:34]: what does this do ?

Comment (saintmatthieu) [reply src/projectscene/view/trackspanel/realtimeeffectlistmodel.cpp:34]: When a project is opened, we update the effect list for all tracks in the project.

Comment (luapmartin) [reply src/projectscene/view/trackspanel/realtimeeffectlistmodel.cpp:34]: like an initialisation right by forcing updates 

should we have a method to wrap that forced update into init() or something like that

**Review by luapmartin — APPROVED** [review]
see if init method make sense

File: src/projectscene/view/trackspanel/realtimeeffectlistmodel.cpp (hunk 1 above)
Comment (saintmatthieu) [reply src/projectscene/view/trackspanel/realtimeeffectlistmodel.cpp:34]: No, it's not for an `init()`  method (which here is just called `load()` - I think the two are interchangeable). For a QtObject, `init()`. is typically called in a `Component.onCompleted`, while this is to be executed each time the current project changes.

Comment (luapmartin) [reply src/projectscene/view/trackspanel/realtimeeffectlistmodel.cpp:34]: `load()` is fine then ok with me

Comment (saintmatthieu) [reply src/projectscene/view/trackspanel/realtimeeffectlistmodel.cpp:34]: 🙏
