### PR TITLE
5901 overflow button

### LINKED ISSUE #5901: Non-destructive pitch shifting: implement overflow button
* A `...` button in the top right corner of clips, which allow to open the clip context menu in one click.
* Pitch and speed indicators become clickable, too.

Figma design (private): https://www.figma.com/file/6kBToiSyv40MOWaNzkxCdj/32_WX---Pitch-%26-Onset-snapping?type=design&node-id=30-761&mode=design&t=PhFBhnaOKVhnO3s8-0

### LINKED ISSUE #5959: Missing clock icon in clip's title bar when time-stretching (Linux)
### Steps to reproduce

1. Have a clip
2. Change its tempo

### Expected behavior

The clock icon is visible

### Actual behavior

image

### Audacity Version

current master / alpha / nightly build

### Operating system

Ubuntu 22.04, Fedora 39 (Appimage)

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #5901

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:
- [ ] See if by chances it fixes #5959 (not mandatory)

### CODE REVIEW

File: src/tracks/playabletrack/wavetrack/ui/ClipOverflowButtonHandle.cpp [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+{
+   return 0;
+}
+
+HitTestPreview ClipOverflowButtonHandle::Preview(
+   const TrackPanelMouseState& state, AudacityProject* pProject)
+{
+   static auto cursor = std::make_unique<wxCursor>(wxCURSOR_HAND);
+   return { XO("Open clip Pitch and Speed menu"), cursor.get(),
+            XO("Pitch and Speed...") };
```
Comment (LWinterberg) [inline src/tracks/playabletrack/wavetrack/ui/ClipOverflowButtonHandle.cpp:85]: It seems like there have been some wires crossed here - the overflow button should summon the clip context menu. Clicking on the pitch/speed numbers should summon the dialog.

**Comment by Paul-Licameli** [comment]
The build fails, in both commits.

Remember `-Daudacity_use_pch=NO` in your Cmake variables.

File: src/tracks/playabletrack/wavetrack/ui/WaveClipUtilities.cpp [hunk 2]
```diff
@@ -100,3 +104,17 @@ void PushClipSpeedChangedUndoState(
        XO("Changed Speed to %.01f%%").Format(speedInPercent),
        UndoPush::CONSOLIDATE);
 }
+
+void ShowClipPitchAndSpeedDialog(
```
Comment (Paul-Licameli) [inline src/tracks/playabletrack/wavetrack/ui/WaveClipUtilities.cpp:108]: Do not put this here.  I'm going to delete this file in my refactoring branch.  Don't complicate my merges of master into the branch.

Just put in the file where the sole call to it is.

Besides which:  this change is extraneous to what the first commit comment says.

File: src/tracks/playabletrack/wavetrack/ui/ClipParameters.h [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+ClipParameters.h
+
+Matthieu Hodgkinson split from class WaveChannelView.h
+
+**********************************************************************/
+#pragma once
+
+class ZoomInfo;
+class ClipTimes;
+
```
Comment (Paul-Licameli) [inline src/tracks/playabletrack/wavetrack/ui/ClipParameters.h:14]: `#include <wx/gdicmn.h>` for `wxRect` is another needed change

File: src/tracks/playabletrack/wavetrack/ui/WaveClipUtilities.cpp [hunk 4]
```diff
@@ -15,8 +15,12 @@
 #include <cassert>
 #include <cmath>
 
+#include "PitchAndSpeedDialog.h"
+#include "ProjectAudioIO.h"
 #include "ProjectHistory.h"
+#include "ProjectWindows.h"
 #include "UndoManager.h"
+#include "WaveTrack.h"
```
Comment (Paul-Licameli) [inline src/tracks/playabletrack/wavetrack/ui/WaveClipUtilities.cpp:23]: As I said, I don't like enlarging this file with the new function, but `#include <wx/frame.h>` would be needed to fix its compilation

File: src/tracks/playabletrack/wavetrack/ui/WaveClipUtilities.cpp (hunk 2 above)
Comment (Paul-Licameli) [reply src/tracks/playabletrack/wavetrack/ui/WaveClipUtilities.cpp:108]: I dislike so called "utility" files unless the things put into them really are needed in more than one place.

File: src/tracks/playabletrack/wavetrack/ui/ClipOverflowButtonHandle.cpp [hunk 5]
```diff
@@ -0,0 +1,103 @@
+#include "ClipOverflowButtonHandle.h"
```
Comment (Paul-Licameli) [inline src/tracks/playabletrack/wavetrack/ui/ClipOverflowButtonHandle.cpp:1]: I could fix the first commit so it compiles -- but then the second fails to link!  You neglected to add the new files to `CMakeLists.txt`.  Also the new files should have banners.

Comment (Paul-Licameli) [reply src/tracks/playabletrack/wavetrack/ui/ClipOverflowButtonHandle.cpp:1]: After I fix CMakeLists.txt, still, to build I must add:

```
#include <wx/window.h>
```

File: src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp [hunk 6]
```diff
@@ -613,17 +627,7 @@ void WaveTrackAffordanceControls::StartEditSelectedClipSpeed(
...
-   PitchAndSpeedDialog dlg(
-      ProjectAudioIO::Get(project).IsAudioActive(), *track, *interval,
-      &GetProjectFrame(project));
-
-   if (wxID_OK == dlg.ShowModal())
-   {
-      ProjectHistory::Get(project).PushState(
-         XO("Changed Pitch and Speed"), XO("Changed Pitch and Speed"),
-         UndoPush::CONSOLIDATE);
-      SelectInterval(project, *interval);
```
Comment (Paul-Licameli) [inline src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp:625]: Again, I don't see the need to move the code -- but also I notice, `SelectInterval` is lost.  Intentional?

File: src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp [hunk 7]
```diff
@@ -613,17 +627,7 @@ void WaveTrackAffordanceControls::StartEditSelectedClipSpeed(
...
-   }
+   ShowClipPitchAndSpeedDialog(project, *track, *interval);
```
Comment (Paul-Licameli) [inline src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp:630]: I was mistaken -- I see it is used in more than one place, now that I fix CMakeLists.txt and rebuild.

**Comment by Paul-Licameli** [comment]
Certainly the build must be fixed!   And there should be banners.

Otherwise it's all right.

**Comment by Paul-Licameli** [comment]
I fix the build, try to run it, generate noise -- and there is a crash.

**Comment by Paul-Licameli** [comment]
So it was at least in a debug build.

File: src/tracks/playabletrack/wavetrack/ui/ClipOverflowButtonHandle.cpp [hunk 8]
```diff
@@ -0,0 +1,103 @@
...
+   return GetButtonRectangle(clipRect).Contains(point);
+}
+
+wxRect
+ClipOverflowButtonHandle::DrawOnClip(wxDC& dc, const wxRect& affordanceRect)
+{
+   const auto rect = GetButtonRectangle(affordanceRect);
+   // Invisible pen
+   constexpr auto penWidth = 0;
+   wxDCPenChanger pen { dc, { wxPenInfo { wxColour {}, penWidth } } };
```
Comment (Paul-Licameli) [inline src/tracks/playabletrack/wavetrack/ui/ClipOverflowButtonHandle.cpp:48]: For me, the debug build was violating an assertion in wxWidgets, but my build didn't have debug symbols and I couldn't see wxWidgets source code.

After some trial and error, I figured out that replacing `wxColour{}` with `*wxBLACK` was a sufficient fix.

File: src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp (hunk 6 above)
Comment (saintmatthieu) [reply src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp:625]: > SelectInterval is lost
It's a tentative removal. The clip still remains selected after the dialog is closed even without. I intended to ask @crsib if he remembered why he added this in 65d23cf019fe465c852a06314981544fc9699dab.

Comment (crsib) [reply src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp:625]: That was literally the task to select the clip on right click. @LWinterberg probably has more details.

**Comment by saintmatthieu** [comment]
@Paul-Licameli thanks for your comments and help, I just pushed fixes.
I moved back this ticket to the progress column because of https://github.com/audacity/audacity/pull/5952#discussion_r1489495326.

**Comment by Paul-Licameli** [comment]
The build is still failing

**Comment by Paul-Licameli** [comment]
You still need `<wx/frame.h>` in WaveClipUtilities

**Comment by Paul-Licameli** [comment]
And the last commit causes new compilation errors

File: src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp [hunk 9]
```diff
@@ -210,17 +210,24 @@ std::vector<UIHandlePtr> WaveTrackAffordanceControls::HitTest(const TrackPanelMo
...
 
-        auto interval = *it;
-        if (WaveChannelView::HitTest(*interval->GetClip(0), zoomInfo, state.rect, {px, py}))
+        const auto clip = (*it)->GetClip(0);
+        if (ClipOverflowButtonHandle::HitTest(
+               *clip, zoomInfo, state.rect, mousePoint))
+        {
+           results.push_back(AssignUIHandlePtr(
+              mOverflowButtonHandle,
+              std::make_shared<ClipOverflowButtonHandle>(track, *it)));
```
Comment (Paul-Licameli) [inline src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp:219]: Need `weak_from_this()` for third argument

File: src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.h [hunk 10]
```diff
@@ -0,0 +1,79 @@
...
+struct ClipButtonDrawingArgs
+{
+   const wxRect& rect;
+   const ClipInterface& clip;
+   wxDC& dc;
+};
+
+namespace ClipButtonSpecializations
+{
+bool NeedsDrawing(ClipButtonTag<ClipButtonId::Overflow>, const ClipInterface&);
```
Comment (vsverchinsky) [inline src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.h:37]: You could avoid introducing extra name `ClipButtonTag`:
```
template<ClipButtonId ID>
class ClipButtonSpecializations final
{
public:
   static bool NeedsDrawing(const ClipInterface&);
   ...
};
extern template<> ClipButtonSpecializations<ClipButtonId::Overflow>;
...
```

File: src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.h [hunk 11]
```diff
@@ -0,0 +1,79 @@
...
+void DrawOnClip(ClipButtonTag<ClipButtonId::Pitch>, ClipButtonDrawingArgs&);
+
+int GetWidth(ClipButtonTag<ClipButtonId::Overflow>);
+int GetWidth(ClipButtonTag<ClipButtonId::Speed>);
+int GetWidth(ClipButtonTag<ClipButtonId::Pitch>);
+} // namespace ClipButtonSpecializations
+
+namespace LowlitClipButton
+{
+struct RectangleArgs
```
Comment (vsverchinsky) [inline src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.h:52]: :eyes:
https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/avoid-const-or-ref-data-members.html
Not the case in that particular set of arguments, but I don't like the idea of wrapping arguments into a structure to shorten the list...

File: src/tracks/playabletrack/wavetrack/ui/HighlitClipButtonHandle.cpp [hunk 12]
```diff
@@ -44,12 +45,27 @@ void HighlitClipButtonHandle::Draw(
 UIHandle::Result HighlitClipButtonHandle::Click(
    const TrackPanelMouseEvent& event, AudacityProject* pProject)
 {
+   mwCell = event.pCell;
```
Comment (vsverchinsky) [inline src/tracks/playabletrack/wavetrack/ui/HighlitClipButtonHandle.cpp:58]: Would be nice to reset `weak_ptr` in `Release` and `Cancel`

File: src/tracks/playabletrack/wavetrack/ui/PitchAndSpeedDialog.cpp [hunk 13]
```diff
@@ -82,6 +82,18 @@ class ScopedVerticalLay : public ScopedSizer<void, int>
...
 };
 
+class ScopedStatic :
+    public ScopedSizer<wxStaticBox*, const TranslatableString&, int>
+{
+public:
+   ScopedStatic(ShuttleGui& s, const TranslatableString& label, int iProp = 0)
+       : ScopedSizer<wxStaticBox*, const TranslatableString&, int>(
+            s, &ShuttleGui::StartStatic, &ShuttleGui::EndStatic,
+            std::move(label), std::move(iProp))
```
Comment (vsverchinsky) [inline src/tracks/playabletrack/wavetrack/ui/PitchAndSpeedDialog.cpp:92]: `label` should be passed by value then, not reference.
`move` on `iProp` is redundant

File: src/tracks/playabletrack/wavetrack/ui/ClipOverflowButtonHandle.cpp [hunk 14]
```diff
@@ -0,0 +1,103 @@
...
+
+   return { affordanceRect.x, affordanceRect.y,
+            affordanceRect.width - rect.width, affordanceRect.height };
+}
+
+UIHandle::Result ClipOverflowButtonHandle::Click(
+   const TrackPanelMouseEvent& event, AudacityProject* pProject)
+{
+   BasicUI::CallAfter(
+      [=] { ShowClipPitchAndSpeedDialog(*pProject, *mTrack, *mClip); });
```
[the remark this answers is not in the document]
Comment (vsverchinsky) [reply src/tracks/playabletrack/wavetrack/ui/ClipOverflowButtonHandle.cpp]: OK, fixed in later commit

File: src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.cpp [hunk 15]
```diff
@@ -0,0 +1,64 @@
...
+
+   // In this order, from left to right: pitch (maybe), speed (maybe), overflow.
+   auto offset = 0;
+   if (buttonId != ClipButtonId::Overflow)
+   {
+      offset += GetWidth(ClipButtonTag<ClipButtonId::Overflow> {});
+      if (
+         buttonId == ClipButtonId::Pitch &&
+         NeedsDrawing(ClipButtonTag<ClipButtonId::Speed> {}, args.clip))
+         offset += GetWidth(ClipButtonTag<ClipButtonId::Speed> {});
```
[the remark this answers is not in the document]
Comment (saintmatthieu) [reply src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.cpp:55]: I agree.

File: src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.h (hunk 10 above)
Comment (saintmatthieu) [reply src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.h:37]: Nice!

File: src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.h (hunk 11 above)
Comment (saintmatthieu) [reply src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.h:52]: First time I read something like this. I do see advantages.

File: src/tracks/playabletrack/wavetrack/ui/PitchAndSpeedDialog.cpp (hunk 13 above)
Comment (saintmatthieu) [reply src/tracks/playabletrack/wavetrack/ui/PitchAndSpeedDialog.cpp:92]: It wasn't when I wrote that line, but that was because of the `Args&&...` in the class template. I removed `&&` and now I don't have to move the ints anymore. I think it's because before it expected right-reference types.

**Review by vsverchinsky — APPROVED** [review]

**Comment by chinakov** [comment]
image

https://github.com/audacity/audacity/issues/5959 this has not been fixed by this PR. The issue is still present on Linux.
