### PR TITLE
Persist snap per project

### LINKED ISSUE #8058: Snapping Does not Persist Per Project Basis
### Bug description

If the User has set a snapping interval in a project, the interval and the toggle will be reset upon opening the same project. 

### Steps to reproduce

1. Launch Audacity
2. Create a new project
3. Add some audio, enable snapping
4. Observe snapping to be functional
5. Close and re-open the project
6. Observe snapping toggle

### Expected behavior

Snapping should be saved on per-project basis.

### Actual behavior

The toggle is reset each time a project has been re-opened. 

### Audacity Version

Audacity 4 alpha

### Operating system

Windows

### Additional context

https://github.com/user-attachments/assets/947d54b1-b165-4b5f-9f48-9eaffc34f36e

### PR DESCRIPTION
**Pull request by embarc-gabriel**
Resolves: #8058

Persist snap information per project.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: src/project/internal/audacityproject.cpp [hunk 1]
```diff
@@ -106,7 +106,7 @@ muse::Ret Audacity4Project::doLoad(const io::path_t& path, bool forceMode, const
     m_trackeditProject = trackeditProjectCreator()->create(m_au3Project);
 
     //! NOTE At the moment, view state don't saved and loaded
-    m_viewState = viewStateCreator()->createViewState();
+    m_viewState = viewStateCreator()->createViewState(m_au3Project);
```
Comment (kryksyh) [inline src/project/internal/audacityproject.cpp:109]: I assume that the comment above is no longer valid? :)

**Review by kryksyh — APPROVED** [review]

File: src/project/internal/audacityproject.cpp (hunk 1 above)
Comment (embarc-gabriel) [reply src/project/internal/audacityproject.cpp:109]: hahaha sure! You right! I put the ticket to QA once the build is already done but I will remove it if there is no QA comment. Thank you!

Comment (embarc-gabriel) [reply src/project/internal/audacityproject.cpp:108]: Done!
