### PR TITLE
Spectrogram context menu and spectral-delete shortcut

### LINKED ISSUE #10190: Spectral editing commands
### Description

Implement the ability to delete/copy/paste spectral selections

### LINKED ISSUE #10445: Spectrogram button in the main toolbar doesn't change its state to active when pressed
Regression since https://github.com/audacity/audacity/commit/f7470b76fbf00a25a15d6c08ad4f3daae42ebbb9

Spectrogram view is enabled, but the button remains inactive:

Image

### LINKED ISSUE #10476: The cursor doesn't change when hovering over the marquee selection when in Spectrogram mode
On hover over the edges of the selection, the cursor should change to a double-headed arrow.

### LINKED ISSUE #10480: Don't rely on out-of-process plugin scanning for nyquist plugins
At the moment, the registration of Nyquist plugins relies on the out-of-process plugin scanning process.

This will be a problem for many among our users who have a lot of 3rd-party plugins (VSTs, etc) especially from the Muse Hub, because the scanning is still slow and sometimes very problematic when one hits the "Missing authorization" issue. Then users (like @Tantacrul) tend to choose "Skip this time".

Consequences:
* Nyquist plugins won't be present,
* The spectrogram context menu will be empty and the spectral-delete shortcut won't work.

### PR DESCRIPTION
**Pull request by saintmatthieu**
- [x] Resolves: #10190
- [x] Resolves: #10445
- [x] Resolves: #10476
- [x] Resolves: https://github.com/audacity/audacity/issues/10393
- [x] Resolves: #10480
- [x] Resolves: https://github.com/audacity/audacity/issues/10491

- [x] Could resolve: https://github.com/audacity/audacity/issues/10517

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:
- [x] Applying Nyquist effect doesn't create new clip (but it does for generators)
- [x] Generators (both nyquist and built-in) behave as expected when passing a duration that's not equal to the selection
- [ ] Autobot test cases have been run

### CODE REVIEW

File: au3/libraries/au3-effects/EffectBase.h [hunk 1]
```diff
@@ -102,6 +102,9 @@ class EFFECTS_API EffectBase /* not final */ : public EffectPlugin
 
     double mF0{ 0. };
     double mF1{ 0. };
+    //! Not necessarily halfway between f0 and f1, e.g. on a logarithmic scale it'd be sqrt(f0*f1).
+    double mCenterFrequency{ 0. };
+
```
Comment (luapmartin) [inline au3/libraries/au3-effects/EffectBase.h:107]: should we name `mF0` `mStartFrequency` and `mF1` `mEndFrequency` to be more consistent ?

Comment (luapmartin) [reply au3/libraries/au3-effects/EffectBase.h:107]: also, is it of to init the mF1 to 0? Shouldn’t we choose a high value? or at least different from mF0?

File: share/nyquist-plug-ins/SpectralEditShelves.ny [hunk 2]
```diff
@@ -1,8 +1,9 @@
 $nyquist plug-in
 $version 5
 $type process spectraltools
+$spectraleffectid AmplifySelection
 $preview linear
-$name (_ "Spectral edit shelves")
+$name (_ "Amplify selection")
 $debugbutton false
```
Comment (luapmartin) [inline share/nyquist-plug-ins/SpectralEditShelves.ny:7]: this sounds like a spectral effect tho it seems it affect the whole frequency range (or at least more than what's just in the selected frequency range) similarly to a non-spectral effect applied to a time range 
I tested in audacity 3 and it seems to behave the same as I can tell.

To my eyes either the name is confusing either there's an issue with that particular spectral effect, maybe we should address this in another PR...

anyway the integration is much more smooth than the OG au3 one, this make 100% more sense and bring much more awareness to those great tool sets, congrats.

File: src/effects/effects_base/internal/effectexecutionscenario.cpp [hunk 3]
```diff
@@ -163,6 +162,7 @@ muse::Ret EffectExecutionScenario::doPerformEffect(au3::Au3Project& project, con
         double t1 = 0.0;
         double f0 = 0.0;
         double f1 = 0.0;
+        double centerFrequency = 0.0;
```
Comment (luapmartin) [inline src/effects/effects_base/internal/effectexecutionscenario.cpp:165]: should we employ more meaningful names for those t1 f1 etc.? now that we have centerFrequency ?

File: src/effects/effects_base/internal/effectexecutionscenario.cpp [hunk 4]
```diff
@@ -197,9 +197,20 @@ muse::Ret EffectExecutionScenario::doPerformEffect(au3::Au3Project& project, con
...
+            // Only pass spectral selection context if all selected clips belong to the same track.
+            if (std::all_of(selectedTracks.begin(), selectedTracks.end(), [trackId](const trackedit::TrackId& id) {
+                return id == trackId;
+            })) {
+                tp.f0 = frequencySelection.startFrequency;
+                tp.f1 = frequencySelection.endFrequency;
+                tp.centerFrequency = frequencySelection.centerFrequency;
+            }
+            tp.spectralSelectionEnabled = spectrogramConfiguration()->spectralSelectionEnabled();
+        }
```
Comment (luapmartin) [inline src/effects/effects_base/internal/effectexecutionscenario.cpp:213]: In au3 we can do multiple spectral selections across several tracks that align on time and frequency, we lost that in au4

File: src/spectrogram/spectrogramtypes.h [hunk 5]
```diff
@@ -71,25 +74,30 @@ struct ViewInfo {
 
 struct FrequencySelection {
     FrequencySelection() = default;
-    FrequencySelection(int trackId, double f1, double f2)
-        : trackId(trackId), startFrequency(std::min(f1, f2)), endFrequency(std::max(f1, f2)) {}
+    FrequencySelection(int trackId, double f1, double f2, double centerFrequency)
```
Comment (luapmartin) [inline src/spectrogram/spectrogramtypes.h]: please change f1 and f2 to start end Frequency

File: src/spectrogram/view/trackspectrogramcontextmenumodel.cpp [hunk 6]
```diff
@@ -0,0 +1,94 @@
...
+        // If the spectral effects above were found, then the following two should be found, too.
+        items.push_back(makeSeparator());
+    }
+
+    if (auto item = makeSpectralEffectItem(SpectralEffectId::AmplifySelection, "Amplify selection")) {
+        items.push_back(item);
+    }
+    if (auto item = makeSpectralEffectItem(SpectralEffectId::AmplifyCenterFrequency, "Amplify selection center frequency")) {
+        items.push_back(item);
+    }
```
Comment (luapmartin) [inline src/spectrogram/view/trackspectrogramcontextmenumodel.cpp]: please modify the makeSpectralEffectItem to lookup the effect title from the registry and avoid that extra param

File: src/spectrogram/view/clipchannelspectrogramview.cpp [hunk 7]
```diff
@@ -158,12 +158,14 @@ void ClipChannelSpectrogramView::paint(QPainter* painter)
...
         return;
     }
-    const int xBegin = std::max(visibleSubrect.left() - m_timelineIndentWidth, 0);
-    const int xEnd = visibleSubrect.right() + 1;
+    const auto boundingRect = this->boundingRect();
+    const QRect rect = mapRectToItem(item, boundingRect).toRect();
+    const int xBegin = std::max(-rect.left() - m_timelineIndentWidth, 0);
+    const int xEnd = xBegin + boundingRect.width();
     const ClipChannelInfo channelInfo { m_clipId, m_trackId, m_channel, xBegin, xEnd };
     const ViewInfo viewInfo {
```
Comment (luapmartin) [inline src/spectrogram/view/clipchannelspectrogramview.cpp:170]: I don't know if it's here but I have some problem with the selection if the user manages to have the same start and end frequency then it produces a odd selection we might prefer to ensure at least 1 frequency diff up / down from start / end to avoid this strange spectral selection without any frequency selected

File: src/spectrogram/qml/Audacity/Spectrogram/TrackSpectralSelectionContainer.qml [hunk 8]
```diff
@@ -23,6 +24,34 @@ Item {
...
+        id: contextMenuMouseArea
+        anchors.fill: parent
+        visible: selectionStartFrequency < selectionEndFrequency
+        hoverEnabled: true
+        acceptedButtons: Qt.RightButton
+        onClicked: function (mouse) {
+            contextMenuLoader.show(Qt.point(mouse.x, mouse.y), contextMenuModel.items)
+        }
+    }
+
```
Comment (luapmartin) [inline src/spectrogram/qml/Audacity/Spectrogram/TrackSpectralSelectionContainer.qml:56]: did you fixed that menu showing at wrong position if clicking on wave track with another track with spectrogram view?

File: src/spectrogram/internal/frequencyselectioncontroller.cpp [hunk 9]
```diff
@@ -23,6 +37,10 @@ void FrequencySelectionController::setFrequencySelection(FrequencySelection freq
     const std::optional<int> previousTrackId
         = m_frequencySelection.isValid() ? std::make_optional(m_frequencySelection.trackId) : std::nullopt;
 
+    frequencySelection.startFrequency = std::max(frequencySelection.startFrequency, 0.0);
+    frequencySelection.endFrequency
+        = std::min(frequencySelection.endFrequency, spectrogramService()->frequencyHardMaximum(frequencySelection.trackId));
+
     if (m_frequencySelection == frequencySelection) {
```
Comment (luapmartin) [inline src/spectrogram/internal/frequencyselectioncontroller.cpp]: maybe we want to ensure at least one frequency exist in the selection

File: src/projectscene/internal/au3/trackviewtypeattachment.cpp [hunk 10]
```diff
@@ -3,9 +3,6 @@
  */
 #include "trackviewtypeattachment.h"
 
-#if AU_MODULE_EFFECTS_NYQUIST
-#include "au3-nyquist-effects/NyquistBase.h"
-#endif
 #include "au3-wave-track/WaveTrack.h"
 
 namespace au::au3 {
```
Comment (luapmartin) [inline src/projectscene/internal/au3/trackviewtypeattachment.cpp:11]: nice

**Review by luapmartin — CHANGES_REQUESTED** [review]

File: au3/libraries/au3-effects/EffectBase.h (hunk 1 above)
Comment (saintmatthieu) [reply au3/libraries/au3-effects/EffectBase.h:107]: > is it of to init the mF1 to 0? Shouldn’t we choose a high value? or at least different from mF0?

I'd like not to try and rework this since it's not caused problems that I know of.

> should we name mF0 mStartFrequency and mF1 mEndFrequency to be more consistent ?

This is AU3 convention. I used `mCenterFrequency` because I don't think there's an existing convention that would guide naming of this particular member, so I just went for this.

File: share/nyquist-plug-ins/SpectralEditShelves.ny (hunk 2 above)
Comment (saintmatthieu) [reply share/nyquist-plug-ins/SpectralEditShelves.ny:7]: I also would have to look more in depth, but it's definitely a spectral effect, as it doesn't amplify the all frequencies equally. Rolloff may be a bit gentle, and even frequency-dependent, it seemed to me (gentler at higher frequencies), which may give this impression.

File: src/effects/effects_base/internal/effectexecutionscenario.cpp (hunk 3 above)
Comment (saintmatthieu) [reply src/effects/effects_base/internal/effectexecutionscenario.cpp:165]: I think it's okay - it uses AU3 convention and this struct reflects the state of an actual AU3 struct.
It's not only time parameters anymore, though - will rename.

File: src/projectscene/internal/au3/trackviewtypeattachment.cpp (hunk 10 above)
Comment (saintmatthieu) [reply src/projectscene/internal/au3/trackviewtypeattachment.cpp:11]: Yes. Now nothing opposes `au3-nyquist-effects` to be migrated to the AU4 Nyquist module.

File: src/spectrogram/internal/frequencyselectioncontroller.cpp (hunk 9 above)
Comment (saintmatthieu) [reply src/spectrogram/internal/frequencyselectioncontroller.cpp]: I'm not sure what good that'd be for. On the other hand, a frequency slice isn't senseless - it already exists as min and max display frequencies can be set to the same value in the settings.

File: src/spectrogram/qml/Audacity/Spectrogram/TrackSpectralSelectionContainer.qml (hunk 8 above)
Comment (saintmatthieu) [reply src/spectrogram/qml/Audacity/Spectrogram/TrackSpectralSelectionContainer.qml:56]: No, but this isn't specific to this PR or to spectrograms.

File: src/spectrogram/view/clipchannelspectrogramview.cpp (hunk 7 above)
Comment (saintmatthieu) [reply src/spectrogram/view/clipchannelspectrogramview.cpp:170]: Here we are dealing with time - finding what leftmost and rightmost pixel column of the clip is visible.
I never stumbled on that kind of strangeness and empty frequency selection. Maybe you can show me sometime. Until then I prefer not to add an arbitrary bandwidth constraint to the frequency selection. Like I said someplace else, showing a frequency slice isn't meaningless.

File: src/spectrogram/spectrogramtypes.h (hunk 5 above)
Comment (saintmatthieu) [reply src/spectrogram/spectrogramtypes.h]: Here it is handy to use those alternative names because of the `std::min` and `max` I call below.

File: src/effects/effects_base/internal/effectexecutionscenario.cpp (hunk 4 above)
Comment (saintmatthieu) [reply src/effects/effects_base/internal/effectexecutionscenario.cpp:213]: Oh, interesting., I wasn't aware, good catch!
Actually, clips on either tracks don't even have to align time or frequency-wise.
Another interaction I found since you pointed this out is ctrl-click: on the same track, it modifies the selection by moving the border closest to the mouse to where the mouse points. On another track, it also duplicates the selection on that new track.
@teetow @Tantacrul FYI

File: src/spectrogram/view/clipchannelspectrogramview.cpp (hunk 7 above)
Comment (luapmartin) [reply src/spectrogram/view/clipchannelspectrogramview.cpp:170]: not sure it will be helpful but it looks like this
image

File: src/spectrogram/qml/Audacity/Spectrogram/TrackSpectralSelectionContainer.qml (hunk 8 above)
Comment (luapmartin) [reply src/spectrogram/qml/Audacity/Spectrogram/TrackSpectralSelectionContainer.qml:56]: ok, I only saw that happening with spectrogram view enabled and right click on wavetrack

File: src/spectrogram/internal/frequencyselectioncontroller.cpp (hunk 9 above)
Comment (luapmartin) [reply src/spectrogram/internal/frequencyselectioncontroller.cpp]: for me 0 frequency selection seems broken so 1 freq slice might put us on the safe side yes

File: au3/libraries/au3-effects/EffectBase.h (hunk 1 above)
Comment (luapmartin) [reply au3/libraries/au3-effects/EffectBase.h:107]: about the init state, if you can't think of any possible issue then we good to go, about naming my take is that it reads a bit inconsistent as "center" for me imply beginning and end and f0 f1 means maybe f2 f3 f99 ... so name update would at least bound the meaning for next dev, choose wisely, thanks, feel free to adjust or not, your call.

File: share/nyquist-plug-ins/SpectralEditShelves.ny (hunk 2 above)
Comment (luapmartin) [reply share/nyquist-plug-ins/SpectralEditShelves.ny:7]: what do you want to do about this? when tested it looked "broken" as the rolloff maybe converted the effect to a full spectrum (maybe a info indicating what rolloff will be applied would guide user?) 
will you rework that effect?

File: src/effects/effects_base/internal/effectexecutionscenario.cpp (hunk 3 above)
Comment (luapmartin) [reply src/effects/effects_base/internal/effectexecutionscenario.cpp:165]: did you ended up renaming ? 
again as said above:

> about naming my take is that it reads a bit inconsistent as "center" for me imply beginning and end and f0 f1 means maybe f2 f3 f99 ... so name update would at least bound the meaning for next dev, choose wisely, thanks, feel free to adjust or not, your call. 

_just adding for t0, t1 we talk about timeStart timeEnd but again not really explicit_

File: src/effects/effects_base/internal/effectexecutionscenario.cpp (hunk 4 above)
Comment (luapmartin) [reply src/effects/effects_base/internal/effectexecutionscenario.cpp:213]: did that got fixed? thanks

File: src/spectrogram/spectrogramtypes.h (hunk 5 above)
Comment (luapmartin) [reply src/spectrogram/spectrogramtypes.h]: I don't understand the rationale sorry

File: src/spectrogram/view/clipchannelspectrogramview.cpp (hunk 7 above)
Comment (luapmartin) [reply src/spectrogram/view/clipchannelspectrogramview.cpp:170]: from our latest conversations I understood this got fixed if yes you can close that comment, thanks

File: src/spectrogram/qml/Audacity/Spectrogram/TrackSpectralSelectionContainer.qml (hunk 8 above)
Comment (luapmartin) [reply src/spectrogram/qml/Audacity/Spectrogram/TrackSpectralSelectionContainer.qml:56]: is it logged ? _(asking to make sure we keep an eye on that)_

File: src/spectrogram/internal/frequencyselectioncontroller.cpp (hunk 9 above)
Comment (luapmartin) [reply src/spectrogram/internal/frequencyselectioncontroller.cpp]: I understand that this got addressed too, right? can close if yes, thanks

File: src/spectrogram/spectrogramtypes.h [hunk 11]
```diff
@@ -107,4 +105,19 @@ struct SpectrogramRulerTicks {
     std::vector<SpectrogramRulerTick> major;
     std::vector<SpectrogramRulerTick> minor;
 };
+
+enum class SpectralEffectId {
+    DeleteSelection,
+    DeleteCenterFrequency,
+    AmplifySelection,
+    AmplifyCenterFrequency,
+};
```
Comment (luapmartin) [inline src/spectrogram/spectrogramtypes.h:116]: those have to be harded-coded right? can't we use the spectraleffectid from nyquist effects?

File: src/uicomponents/qml/Audacity/UiComponents/components/MarqueeSelection.qml [hunk 12]
```diff
@@ -114,29 +114,29 @@ Canvas {
...
     }
 
     CornerHandle {
         id: bottomLeft
-        x: -bottomLeft.width / 2
-        y: parent.height - bottomLeft.height / 2
+        x: 0
+        y: parent.height - bottomLeft.height
         size: prv.edgeWidth
     }
```
Comment (luapmartin) [inline src/uicomponents/qml/Audacity/UiComponents/components/MarqueeSelection.qml:141]: neat

File: share/nyquist-plug-ins/SpectralEditShelves.ny (hunk 2 above)
Comment (saintmatthieu) [reply share/nyquist-plug-ins/SpectralEditShelves.ny:7]: I definitely won't rework that effect in this PR. I am not too concerned but maybe I'm wrong. Feel free to add a checkbox for QA on this so that they evaluate and if they're unhappy we'll think of a follow-up ticket.

File: src/effects/effects_base/internal/effectexecutionscenario.cpp (hunk 3 above)
Comment (saintmatthieu) [reply src/effects/effects_base/internal/effectexecutionscenario.cpp:165]: I'm still of the opinion that it's okay this way :shrug:

File: src/effects/effects_base/internal/effectexecutionscenario.cpp (hunk 4 above)
Comment (saintmatthieu) [reply src/effects/effects_base/internal/effectexecutionscenario.cpp:213]: No, we decided in a follow-up meeting together with @teetow (I think you were present, too?) to leave it this way. The use case (multi-channel recording and wanting to eliminate one noise across all channels at once) is rather marginal. If it turns out that we've underestimated it we'll find out and act on it then.

File: src/spectrogram/view/clipchannelspectrogramview.cpp (hunk 7 above)
Comment (saintmatthieu) [reply src/spectrogram/view/clipchannelspectrogramview.cpp:170]: Yes it got fixed - now a frequency selection of bandwidth 0 will still be visible and resizeable.

File: src/spectrogram/internal/frequencyselectioncontroller.cpp [hunk 13]
```diff
@@ -4,54 +4,74 @@
...
+    }
+}
+
 FrequencySelection FrequencySelectionController::frequencySelection() const
 {
     return m_frequencySelection;
 }
 
-void FrequencySelectionController::setFrequencySelection(FrequencySelection frequencySelection)
+void FrequencySelectionController::setFrequencySelection(FrequencySelection frequencySelection, bool complete)
```
Comment (luapmartin) [inline src/spectrogram/internal/frequencyselectioncontroller.cpp:50]: what is that `complete` about? I got puzzled by this name

File: src/effects/effects_base/internal/effectexecutionscenario.cpp (hunk 3 above)
Comment (luapmartin) [reply src/effects/effects_base/internal/effectexecutionscenario.cpp:165]: as you prefer, you said above "will rename" so I wanted to check if it was still pending or not, (_and if you were to make those changes wanted also to double check if the t would also benefit from the changes_) your call here, thanks.

File: src/spectrogram/spectrogramtypes.h (hunk 11 above)
Comment (luapmartin) [reply src/spectrogram/spectrogramtypes.h:116]: and the spectral effects register/registry ? for which those effect would be registered ?

File: src/effects/effects_base/internal/effectexecutionscenario.cpp (hunk 3 above)
Comment (saintmatthieu) [reply src/effects/effects_base/internal/effectexecutionscenario.cpp:165]: The "will rename" related to the naming of the struct, which used to be `EffectTimeParams` (but it's also been frequency params for a while now).
Thanks for your understanding.

File: src/spectrogram/internal/frequencyselectioncontroller.cpp (hunk 13 above)
Comment (saintmatthieu) [reply src/spectrogram/internal/frequencyselectioncontroller.cpp:50]: Until you have released the mouse, it will be false.
This was to address one good comment from the robot about reloading menus at high rate while dragging the frequency selection.

File: src/spectrogram/qml/Audacity/Spectrogram/TrackSpectralSelectionContainer.qml (hunk 8 above)
Comment (saintmatthieu) [reply src/spectrogram/qml/Audacity/Spectrogram/TrackSpectralSelectionContainer.qml:56]: Yes

File: src/spectrogram/spectrogramtypes.h (hunk 11 above)
Comment (saintmatthieu) [reply src/spectrogram/spectrogramtypes.h:116]: That's how I did dependency inversion: some module can register an effect for any of these four guys. Right now it's the nyquist module setting all of them, but in principle it could be the built-in or another module. Maybe we'll want to ship a GPL-3 VST that does a better job at either of these :)

Comment (saintmatthieu) [reply src/spectrogram/spectrogramtypes.h:116]: > and the spectral effects register/registry ? for which those effect would be registered ?

I don't understand that question.

File: src/spectrogram/spectrogramtypes.h (hunk 5 above)
Comment (saintmatthieu) [reply src/spectrogram/spectrogramtypes.h]: The ctor adds a safety in case someone constructs a frequency selection with mixed up start and end frequencies. If I used `startFrequency` and `endFrequency` instead of `f1` and `f2`, I'd get `startFrequency(std::min(startFrequency, endFrequency))`, you see?

Comment (luapmartin) [reply src/spectrogram/spectrogramtypes.h]: ok

File: src/spectrogram/spectrogramtypes.h (hunk 11 above)
Comment (luapmartin) [reply src/spectrogram/spectrogramtypes.h:116]: ok

File: src/spectrogram/internal/frequencyselectioncontroller.cpp (hunk 13 above)
Comment (luapmartin) [reply src/spectrogram/internal/frequencyselectioncontroller.cpp:50]: maybe renaming to `isDragging` and inverse it ?  or some name related to mouse action happening, thanks

Comment (saintmatthieu) [reply src/spectrogram/internal/frequencyselectioncontroller.cpp:50]: Maybe you never came across this, but this terminology is used in other places of AU4 (look for `bool complete` or `bool completed`) and it always has this meaning, I think. It may not have been the best choice from the start, but you just have to understand it once, so the price to pay is relatively low IMO.

File: au3/libraries/au3-wave-track/WaveTrack.cpp [hunk 14]
```diff
@@ -1332,8 +1332,23 @@ void WaveTrack::ClearAndPaste(
...
+            if (clipsBefore[i]->GetPlayStartTime() != clipsAfter[i]->GetPlayStartTime()
+                || clipsBefore[i]->GetPlayEndTime() != clipsAfter[i]->GetPlayEndTime()) {
+                return;
+            }
+        }
+        for (size_t i = 0; i < clipsBefore.size(); ++i) {
+            clipsAfter[i]->SetId(clipsBefore[i]->GetId());
+        }
+    }
 }
```
Comment (luapmartin) [inline au3/libraries/au3-wave-track/WaveTrack.cpp:1352]: I guess it's ok with undo/redo right?

File: src/spectrogram/internal/frequencyselectioncontroller.cpp (hunk 13 above)
Comment (luapmartin) [reply src/spectrogram/internal/frequencyselectioncontroller.cpp:50]: never ever but thanks for the explanation

**Review by luapmartin — APPROVED** [review]
Approved, the last question would be that with such a dense feature and lot of little know-how here and there, would proper unit testing make sense to avoid (control) regressions?
I guess there is low hanging fruits in terms of basic operation that would cover a wide range of cases that QA wont have to venture on testing each and every time.

File: au3/libraries/au3-wave-track/WaveTrack.cpp (hunk 14 above)
Comment (saintmatthieu) [reply au3/libraries/au3-wave-track/WaveTrack.cpp:1352]: I think so, yes.

**Comment by chinakov** [comment]
Issues outlined in the QA checklist above have been fixed.
