### PR TITLE
7573 crash on close due to undoable unsaved changes

### LINKED ISSUE #7573: A crash when trying to undo/redo adding and reordering of the effect on the master
### Bug description

_No response_

### Steps to reproduce

1. Generate a rhythm track
2. Add a built-in effect to the master (e.g. Bass and treble)
3. Turn OFF and then turn ON the entire master effects chain by clicking the blue power button
4. `Edit > Undo` x2
5. Observe: the rhythm track clip is gone
6. `Edit > Redo`
7. Observe: the rhythm track clip is back
8. Click Play
9. Click Stop
10. Ctrl (Cmd) + W -> "No"

### Expected behavior

No crash; the project is closed.

### Actual behavior

A crash:

https://github.com/user-attachments/assets/2509bed6-c704-451a-8915-6c46267da781

### Audacity Version

Audacity 3.7.x

### Operating system

macOS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #7573 

`UndoManager::MarkUnsaved()` resets its `int state` member to -1. `MarkUnsaved()` is used when toggling realtime effects on or off. On the other hand, 99f1314b16bcb74d0c52a3135bf7bde541f3b72f introduced a call to
```
ProjectHistory::Get(project).SetStateTo(undoManager.GetSavedState(), ...);
``` 
but `GetSavedState()` was now returning -1 meanwhile `SetStateTo` was expecting an `unsigned int` ... Hence the crash.

`MarkUnsaved()` resetting `state` to -1 makes the undo manager loose track of the last saved state. Simply making `SetStateTo` robust against calls with `-1` is sufficient to fix the crash but leaves the possibility that the user changes something (e.g. project tempo), toggles a realtime effect, says "No, I don't want to save" when closing, and yet, when reopening her project, sees that the change was saved nevertheless.

 , thereby loosing track of particular unsaved actions. When closing and saying "No, don't save changes", the state of the project can't be reverted to the last saved change anymore because `GetSavedState()` returns -1 and is hence unusable.

The proposed solution gets `MarkUnsaved` not to reset `state` to -1. Reviewers should verify that this doesn't have unintended side effects.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by saintmatthieu** [comment]
Provided that this fix works as intended, the changes in the `UndoManager` and `ProjectHistory` will have to be ported to AU4. @ianalarina FYI

File: src/BatchCommands.cpp [hunk 1]
```diff
@@ -698,7 +698,6 @@ bool MacroCommands::ApplyMacro(
             undoManager.Undo(
                [&]( const UndoStackElem &elem ){
                   history.PopState( elem.state ); } );
-            undoManager.AbandonRedo();
```
Comment (saintmatthieu) [inline src/BatchCommands.cpp:701]: This shouldn't cause a problem: when reaching this stage, the macro has already pushed a new state, which means `AbandonRedo()` has already been called. At this stage, calling it again is trivial: there is nothing to undo already.

File: libraries/lib-project-history/UndoManager.cpp [hunk 2]
```diff
@@ -254,9 +247,8 @@ void UndoManager::PushState(const TranslatableString &longDescription,
 
 void UndoManager::AbandonRedo()
 {
-   if (saved > current) {
-      saved = -1;
-   }
+   if (mSaved.GetValue() > current)
+      mSaved.SetValue(-1);
```
Comment (kryksyh) [inline libraries/lib-project-history/UndoManager.cpp:251]: Does it make sense to add 'Reset' method?

File: libraries/lib-project-history/UndoManager.cpp [hunk 3]
```diff
@@ -228,11 +226,6 @@ void UndoManager::PushState(const TranslatableString &longDescription,
        lastAction.Translation() == longDescription.Translation() &&
        mayConsolidate ) {
       ModifyState();
-      // MB: If the "saved" state was modified by ModifyState, reset
-      //  it so that UnsavedChanges returns true.
-      if (current == saved) {
-         saved = -1;
-      }
       return;
```
Comment (kryksyh) [inline libraries/lib-project-history/UndoManager.cpp:229]: I believe we need a call to MarkUnsaved() here

File: libraries/lib-project-history/UndoManager.cpp [hunk 4]
```diff
@@ -141,8 +139,8 @@ void UndoManager::RemoveStates(size_t begin, size_t end)
 
       if (current > begin)
         --current;
-      if (saved > static_cast<int>(begin))
-        --saved;
+      if (mSaved.GetValue() > static_cast<int>(begin))
```
Comment (kryksyh) [inline libraries/lib-project-history/UndoManager.cpp:142]: cast is no longer needed

File: libraries/lib-project-history/UndoManager.cpp (hunk 3 above)
Comment (saintmatthieu) [reply libraries/lib-project-history/UndoManager.cpp:229]: I think you're right. The comment mislead me (`ModifyState()` in fact never changed `saved`), yet is a new state is pushed, of course there is something to save.

File: libraries/lib-project-history/UndoManager.cpp (hunk 4 above)
Comment (saintmatthieu) [reply libraries/lib-project-history/UndoManager.cpp:142]: Why not?

Comment (saintmatthieu) [reply libraries/lib-project-history/UndoManager.cpp:142]: Right. May address on rebase.

**Review by kryksyh — APPROVED** [review]

**Comment by saintmatthieu** [comment]
For now I reverted the changes that did not just strictly fixed the reported crash.
I haven't found a fix that doesn't cause some sort of regression so far.
