### PR TITLE
8067 toggling effect makes project dirty

### LINKED ISSUE #8067: Turning an effect on and off doesn't make the project dirty
### Bug description

_No response_

### Steps to reproduce

1. Create a new project 
2. Add a track
3. Add an effect to it
4. Save it 
5. Turn the effect off
6. Try to close it

### Expected behavior

The user is asked if they want to save the project.

### Actual behavior

The project is closed right away.

### Audacity Version

Audacity 4 alpha

### Operating system

macOS, Windows, Linux

### Additional context

Discovered while testing https://github.com/audacity/audacity/pull/7997

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #8067 

The fix of 8067 for track effects was easy, only needed the project to be made dirty.

For master effects, however, this was more complicated, and also is a defect on AU3.
The reason is that track effects are attachments of wave tracks, whose management when opening, making the project dirty and saving, was carefully implemented. The track attachments benefit from this maintenance. The maintenance of the project effects needed its own implementation.

Also, this ticket addresses an issue we have on master: create an empty project, save it, generate a 1h tone, close without saving: the project size is still several hundred MBs. (see #7312 wrt AU3). This must be implemented with care, though, that it doesn't lead to another issue, see #7382. The logic seen is similar to what can be found in `./au3/src/ProjectManager.cpp`.
This is addressed in this PR because solving this also helps fixing the original purpose of this ticket or "toggling effect makes project dirty".

Another issue this solves (although there wasn't a ticket for it) is that, when closing a project with unsaved changes, the solution so far was to rewind the history, which sometimes was also visible in the UI and looking a bit silly.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:
- [x] Project is compacted on close: create new project, save, generate 1h tone, close without saving: the project file should be about 20KB, not several megs. (See #7312 for more information. Was fixed for AU3 but not implemented in AU4.)
- [x] When creating a new project or opening an empty project, the master effect power button is enabled.
- [x] Toggling the power button of either master or track effects makes the project dirty
- [x] When closing and re-opening project (including re-starting application), power button states is correct whether saving changes or not before closing

### CODE REVIEW

File: au3/libraries/lib-realtime-effects/SavedMasterEffectList.cpp [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+{
+    UpdateCopy();
+}
+
+void SavedMasterEffectList::UpdateCopy()
+{
+    mLastSavedList = std::make_unique<RealtimeEffectList>(RealtimeEffectList::Get(m_project));
+}
+
+static const AudacityProject::AttachedObjects::RegisteredFactory key2{
```
Comment (kryksyh) [inline au3/libraries/lib-realtime-effects/SavedMasterEffectList.cpp:18]: now that it is in a separate file it could be renamed to `key`

**Review by kryksyh — APPROVED** [review]

**Review by igorkorsukov — APPROVED** [review]

**Comment by dozzzzer** [comment]
@saintmatthieu Turning individual effects on and off doesn't make the project dirty while doing so on an entire stack does.

**Review by kryksyh — APPROVED** [review]
