### PR TITLE
5799: Catch failing AudioUnit UI loading

### LINKED ISSUE #5799: (macOS) Crash when launching AUMultibandCompressor
### Bug description

Attempting to use AUMultibandCompressor results in crash every time

### Steps to reproduce

1 - open audio file
2- select audio 
3 - open AUMultibandCompressor

### Expected behavior

AUMultibandCompressor should appear, instead app crashes

### Actual behavior

crash

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #5799 5799

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: src/effects/audiounits/AUControl.mm [hunk 1]
```diff
@@ -291,10 +291,14 @@ - (void)cocoaViewResized:(NSNotification *)notification
             if (auto factoryClass = [bundle classNamed:viewClass])
                // Create an instance of the class
                if (id factoryInst = [[[factoryClass alloc] init] autorelease])
-                  // Create the view, suggesting a reasonable size
-                  if ((mView = [factoryInst uiViewForAudioUnit:mUnit
-                                                 withSize:NSSize{800, 600}]))
+                 // Create the view, suggesting a reasonable size
+                 try {
+                   if ((mView =
```
Comment (crsib) [inline src/effects/audiounits/AUControl.mm:296]: I don't understand why this works. I assume, that you try to catch Obj-C exception, and the syntax is different https://stackoverflow.com/questions/4648952/objective-c-exceptions

Comment (saintmatthieu) [reply src/effects/audiounits/AUControl.mm:296]: I guess because objective-c++ exceptions are derived from c++ exceptions.

**Review by crsib — APPROVED** [review]
