### PR TITLE
8918 8995 8990 8808 Playback meter improvements

### LINKED ISSUE #8808: A black notch indicating peak is visible as soon as the new track is added
1. Create a new track
2. Observe: The black notch already sits at the bottom of the track meter 

Image

### LINKED ISSUE #8918: Playback meter: minor UI issues
#### 1. There should be _some_ room below -60 dB. There's none currently.

Image

#### 2. The bottom of the L/R meters should be rounded, too.

Image

#### 3. The bottom of the track control panel is slightly off on Windows:

Image

### LINKED ISSUE #8990: The per-track meter's bottom jumps up and down when it indicates clipping
https://github.com/user-attachments/assets/fd474b29-f4ec-4762-b813-9d00884dd262

### LINKED ISSUE #8995: Wrong initial slider position when volume is not the default on the playback meter
### Bug description

The slider position is initialized after changing the meter position.

### Steps to reproduce

1. On the horizontal playback meter change the volume
2. Change the meter position to vertical
3. Change it back to horizontal

### Expected behavior

The slider position should remain the same

### Actual behavior

The slider position is initialize but the volume has really changed.

### Audacity Version

master

### Operating system

OS independent

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by embarc-gabriel**
Resolves: #8918 
Resolves: #8995
Resolves: #8990
Resolves: #8808 

This PR fixes small UI issues and also some bugs related to playback meters.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by kryksyh — APPROVED** [review]

File: src/playback/internal/meters/linearmeter.cpp [hunk 1]
```diff
@@ -50,6 +52,10 @@ double LinearMeter::stepToPosition(double step) const
 
 double LinearMeter::sampleToPosition(double sample) const
 {
+    if (sample == MIN_VOLUME_DB) {
```
Comment (luapmartin) [inline src/playback/internal/meters/linearmeter.cpp]: should this double equality be approximated ?

File: src/playback/internal/meters/linearmeter.cpp [hunk 2]
```diff
@@ -50,6 +52,10 @@ double LinearMeter::stepToPosition(double step) const
...
+        return 0.0;
```
Comment (luapmartin) [inline src/playback/internal/meters/linearmeter.cpp]: `0.0` is this `MIN_VOLUME_LIN` or something else?

File: src/playback/internal/meters/linearmeter.cpp [hunk 3]
```diff
@@ -16,6 +16,8 @@ using namespace au::playback;
 static constexpr double MIN_VOLUME_LIN = 0.0;
 static constexpr double MAX_VOLUME_LIN = 1.0;
 
+static constexpr double MIN_VOLUME_DB = -60.0;
+
```
Comment (luapmartin) [inline src/playback/internal/meters/linearmeter.cpp:20]: do we also need a `MAX_VOLUME_DB` ?

**Review by luapmartin — APPROVED** [review]

File: src/playback/internal/meters/linearmeter.cpp (hunk 1 above)
Comment (embarc-gabriel) [reply src/playback/internal/meters/linearmeter.cpp]: You are absolutely right!
Thank you!
Fixed.

File: src/playback/internal/meters/linearmeter.cpp (hunk 2 above)
Comment (embarc-gabriel) [reply src/playback/internal/meters/linearmeter.cpp]: Fixed.

File: src/playback/internal/meters/linearmeter.cpp (hunk 3 above)
Comment (embarc-gabriel) [reply src/playback/internal/meters/linearmeter.cpp:20]: No ... the value is clipped later on.
