### PR TITLE
9086 track ruler zoom

### LINKED ISSUE #9086: Track vertical ruler - allow ruler to zoom in
### Description

[Figma link](https://www.figma.com/design/PIavx2Q7WayFAw2FQORrTw/09---Timeline---rulers?node-id=1061-11332&p=f&t=R0tIlKBGflSD1n7I-0)

### LINKED ISSUE #9088: Track vertical ruler - Adjust waveform on ruler change
### Description

[Figma link](https://www.figma.com/design/PIavx2Q7WayFAw2FQORrTw/09---Timeline---rulers?node-id=1061-11332&p=f&t=R0tIlKBGflSD1n7I-0)

### LINKED ISSUE #9840: Show Vertical Ruler Checkmark Persists if Disabled via Track
### Bug description

If the User disables the vertical ruler via the flyout that's available within a track, the View -> Show Vertical Rulers will still be shown as enabled. 

### Steps to reproduce

1. Launch AU4
2. Enable Vertical Ruler via View -> Show vertical ruler
3. Click on the Vertical Ruler
4. Disable 'Show vertical rulers' 
5. Go back to View -> Show vertical ruler
6. Observe Show vertical ruler is still enabled

### Expected behavior

Vertical ruler is not shown to be enabled in the View menu. 

### Actual behavior

Vertical ruler is shown to be enabled in the View menu. 

### Audacity Version

da18a3aab3eb3b0c0c3988976fd0a674fc21e7fd

### Operating system

OS independent

### Additional context

https://github.com/user-attachments/assets/3b885010-7e79-4b17-b520-df0cf9e5b6c6

### PR DESCRIPTION
**Pull request by embarc-gabriel**
Resolves: https://github.com/audacity/audacity/issues/9086 
Resolves: #9840 
Resolves: https://github.com/audacity/audacity/issues/9088

This ticket implements vertical zoom.
For DB ruler types, we decided to keep only integer DB values on the ruler.
We also need to take the db range into account for linear rulers. Not allowing zoom in more than needed.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:

- [ ] Autobot test cases have been run

### CODE REVIEW

File: src/trackedit/itracksinteraction.h [hunk 1]
```diff
@@ -65,6 +65,10 @@ class ITracksInteraction : MODULE_EXPORT_INTERFACE
     virtual bool makeStereoTrack(const TrackId left, const TrackId right) = 0;
     virtual bool resampleTracks(const TrackIdList& tracksIds, int rate) = 0;
 
+    virtual void verticalZoomIn(const trackedit::TrackId& trackId) = 0;
+    virtual void verticalZoomOut(const trackedit::TrackId& trackId) = 0;
```
Comment (saintmatthieu) [inline src/trackedit/itracksinteraction.h]: Minor: why not using a verb here, `zoomInVertically` / `zoomOutVertically` ?

File: src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp [hunk 2]
```diff
@@ -301,6 +306,39 @@ bool ViewTracksListModel::isVerticalRulersVisible() const
...
+            //Only linear rulers contain decimal places.
+            continue;
+        }
+
+        // Find the smallest vertical zoom among linear rulers to ajust the width globally.
+        smallestBoundValue = std::min(smallestBoundValue, track.verticalZoom);
+    }
+    smallestBoundValue *= 0.1f;
+
+    const double EPSILON = 1e-9;
```
Comment (saintmatthieu) [inline src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp]: Minor: could also be constexpr (for local consistency)

Comment (saintmatthieu) [reply src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp]: Shouldn't this better be a `float` too?

File: src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp [hunk 3]
```diff
@@ -301,6 +306,39 @@ bool ViewTracksListModel::isVerticalRulersVisible() const
...
+    float decimalPart = smallestBoundValue - static_cast<int>(smallestBoundValue);
+
+    while (std::abs(decimalPart) > EPSILON) {
+        decimalPart *= 10;
+        decimalPart = decimalPart - static_cast<int>(decimalPart);
+        count++;
+        if (count == MAX_DECIMAL_PLACES) {
+            break;
+        }
+    }
```
Comment (saintmatthieu) [inline src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp]: I like to place these in a `constexpr int numDecimals` function, then you can statically test it,
```
static_assert(numDecimals(1.01)) == 2;
static_assert(numDecimals(1.00)) == ?;
```

File: src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp [hunk 4]
```diff
@@ -301,6 +306,39 @@ bool ViewTracksListModel::isVerticalRulersVisible() const
     return projectSceneConfiguration()->isVerticalRulersVisible();
 }
 
+int ViewTracksListModel::verticalRulerWidth() const
```
Comment (saintmatthieu) [inline src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp:339]: I've looked at the commit "feat(rulers): change ruler width based on linear ruler precision" and still I can't find out how ruler precision can be changed?

File: src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp [hunk 5]
```diff
@@ -289,9 +293,10 @@ QHash<int, QByteArray> ViewTracksListModel::roleNames() const
         { IsLinearRole, "isLinear" },
         { AvailableRulerTypesRole, "availableRulerTypes" },
         { TrackRulerTypeRole, "trackRulerType" },
+        { DbRangeRole, "dbRange" },
+        { VerticalZoomRole, "verticalZoom" },
```
Comment (saintmatthieu) [inline src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp]: It may seem redundant, but it'd be helpful to use `trackVerticalZoom`: there seems to be many `verticalZoom`s already and looking for where it's used via text search yields a lot of false positives.

File: src/au3wrap/internal/domconverter.cpp [hunk 6]
```diff
@@ -77,7 +78,21 @@ au::trackedit::TrackViewType trackViewType(const Au3Track* track)
...
+float trackVerticalZoom(const Au3Track* track)
+{
+    const auto* waveTrack = dynamic_cast<const WaveTrack*>(track);
+    if (waveTrack == nullptr) {
+        return 0.0f;
+    }
+
+    const auto& cache = WaveformScale::Get(*waveTrack);
+    float min;
+    float max;
```
Comment (saintmatthieu) [inline src/au3wrap/internal/domconverter.cpp]: Maybe initializing to zero would be safer? It's not clear that `GetDisplayBounds` always modifies these inputs.

File: src/projectscene/view/trackruler/itrackruler.h [hunk 7]
```diff
@@ -32,5 +32,6 @@ class ITrackRulerModel
     [[nodiscard]] virtual std::string sampleToText(double sample) const = 0;
```
Comment (saintmatthieu) [inline src/projectscene/view/trackruler/itrackruler.h:32]: Comment about the `ITrackRulerModel` name (not due to this PR): I thought it was a view model. Wouldn't `ITrackRuler` be sufficient and less confusing?

**Review by saintmatthieu — APPROVED** [review]
Comments mostly about naming, nothing major - may move to QA while they (maybe) get addressed.

File: src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp (hunk 4 above)
Comment (embarc-gabriel) [reply src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp:339]: If you zoom in, the linear ruler's step size changes. At first we have 1.0, 0.9, 0.8 ...
If I zoom in once 0.50, 0.45, 0.40 ...

File: src/projectscene/view/trackruler/itrackruler.h (hunk 7 above)
Comment (embarc-gabriel) [reply src/projectscene/view/trackruler/itrackruler.h:32]: Done.

File: src/au3wrap/internal/domconverter.cpp (hunk 6 above)
Comment (embarc-gabriel) [reply src/au3wrap/internal/domconverter.cpp]: Done.

File: src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp (hunk 5 above)
Comment (embarc-gabriel) [reply src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp]: Done.

File: src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp (hunk 3 above)
Comment (embarc-gabriel) [reply src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp]: Done.

File: src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp (hunk 2 above)
Comment (embarc-gabriel) [reply src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp]: Done

File: src/trackedit/itracksinteraction.h (hunk 1 above)
Comment (embarc-gabriel) [reply src/trackedit/itracksinteraction.h]: Done.

File: src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp (hunk 4 above)
Comment (saintmatthieu) [reply src/projectscene/view/tracksitemsview/viewtrackslistmodel.cpp:339]: Exactly: I didn't manage to get it to two decimal places, not matter how far I zoomed. (It didn't feel buggy, though, so maybe my track wasn't high enough.)
