### PR TITLE
Extract lib exceptions

### LINKED ISSUE #1162: Extract lib-exceptions
Depends on #1059 

Two hours

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves #1162

Toolkit neutral library for Audacity's exception handling system

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

File: src/AudacityException.cpp [hunk 1]
```diff
@@ -20,6 +20,21 @@ AudacityException::~AudacityException()
 {
 }
 
+void AudacityException::EnqueueAction(
```
Comment (vsverchinsky) [inline src/AudacityException.cpp:22]: This PR introduces changes not directly related to the general purpose of this PR as i understand it. Also it introduces changes that will never be tested, however i do agree with neccessity of breaking complex action like "move and change" into separate steps

**Review by vsverchinsky — APPROVED** [review]

File: src/AudacityException.cpp (hunk 1 above)
Comment (Paul-Licameli) [reply src/AudacityException.cpp:22]: Which changes do you think are unrelated?  I tried to explain reasons sufficiently in commit comments.

Comment (vsverchinsky) [reply src/AudacityException.cpp:22]: moving CallAfter to EnqueueAction, and the description of this commit is indeed related to it's contents, but the commit itself does something that is not neccessary for this PR. And d45887740d738f22c80f77614a390b0ec41d5b65 also looks out of place (fix to a BasicUI)

Comment (Paul-Licameli) [reply src/AudacityException.cpp:22]: Understand that without commit d458877, this PR will fail to build on Windows, with link errors.

Comment (Paul-Licameli) [reply src/AudacityException.cpp:22]: CallAction is first moved out of an inline function, and into the .cpp file, so wx/app.h can be removed from the header file.  That requires adjustment of many other #include directives elsewhere.  So, I made a commit mostly about just those routine adjustments, separately, before presenting other changes in other commits.

Comment (Paul-Licameli) [reply src/AudacityException.cpp:22]: Ultimately wx/app.h must disappear from the .cpp as well as the .h file, so that I can claim that this new library is sufficiently toolkit-neutral.  I do that in another commit.

So yes, the total sequence of changes includes an intermediate state of the code transformation, which is never tested.  But I believe none the less that it is better to preserve a record of code transformations that are individually easier to review.
