### PR TITLE
PortAudio update

### LINKED ISSUE #871: AudioIO uses private PaUtil_GetTime API of PortAudio
PaUtil_GetTime is defined in [src/common/pa_util.h in PortAudio](https://github.com/PortAudio/portaudio/blob/master/src/common/pa_util.h). This header is not installed by the build system as confirmed by checking the files installed by Fedora's portaudio-devel package:
```
❯ rpm -ql portaudio-devel
/usr/include/pa_jack.h
/usr/include/pa_linux_alsa.h
/usr/include/pa_unix_oss.h
/usr/include/portaudio.h
/usr/include/portaudiocpp
/usr/include/portaudiocpp/AutoSystem.hxx
/usr/include/portaudiocpp/BlockingStream.hxx
/usr/include/portaudiocpp/CFunCallbackStream.hxx
/usr/include/portaudiocpp/CallbackInterface.hxx
/usr/include/portaudiocpp/CallbackStream.hxx
/usr/include/portaudiocpp/CppFunCallbackStream.hxx
/usr/include/portaudiocpp/Device.hxx
/usr/include/portaudiocpp/DirectionSpecificStreamParameters.hxx
/usr/include/portaudiocpp/Exception.hxx
/usr/include/portaudiocpp/HostApi.hxx
/usr/include/portaudiocpp/InterfaceCallbackStream.hxx
/usr/include/portaudiocpp/MemFunCallbackStream.hxx
/usr/include/portaudiocpp/PortAudioCpp.hxx
/usr/include/portaudiocpp/SampleDataFormat.hxx
/usr/include/portaudiocpp/Stream.hxx
/usr/include/portaudiocpp/StreamParameters.hxx
/usr/include/portaudiocpp/System.hxx
/usr/include/portaudiocpp/SystemDeviceIterator.hxx
/usr/include/portaudiocpp/SystemHostApiIterator.hxx
/usr/lib64/libportaudio.so
/usr/lib64/libportaudiocpp.so
/usr/lib64/pkgconfig/portaudio-2.0.pc
/usr/lib64/pkgconfig/portaudiocpp.pc
```

pa_util.h is not listed in the [PortAudio documentation](http://files.portaudio.com/docs/v19-doxydocs/group__public__header.html) either. Audacity is using a private function of PortAudio. This prevents linking Audacity to packages of PortAudio.

The code that uses PaUtil_GetTime is guarded by an #ifdef:
```
#ifdef EXPERIMENTAL_MIDI_OUT
// return the system time as a double
static double streamStartTime = 0; // bias system time to small number

static double SystemTime(bool usingAlsa)
{
#ifdef __WXGTK__
   if (usingAlsa) {
      struct timespec now;
      // CLOCK_MONOTONIC_RAW is unaffected by NTP or adj-time
      clock_gettime(CLOCK_MONOTONIC_RAW, &now);
      //return now.tv_sec + now.tv_nsec * 0.000000001;
      return (now.tv_sec + now.tv_nsec * 0.000000001) - streamStartTime;
   }
#else
   static_cast<void>(usingAlsa);//compiler food.
#endif

   return PaUtil_GetTime() - streamStartTime;
}
#endif
```

So I tried building with the `-Daudacity_use_portaudio=system -DUSE_PORTMIXER=OFF` CMake options and the patch below to use the system PortAudio without Audacity's PortMixer fork which requires Audacity's PortAudio fork to build and without MIDI support:
```
diff --git a/cmake-proxies/CMakeLists.txt b/cmake-proxies/CMakeLists.txt
index 35250773c..c3ffc4710 100644
--- a/cmake-proxies/CMakeLists.txt
+++ b/cmake-proxies/CMakeLists.txt
@@ -13,7 +13,7 @@ addlib( expat              expat       EXPAT       YES   YES   "expat >= 2.1.0"
 addlib( lame               lame        LAME        YES   YES   "lame >= 3.100" )
 addlib( libsndfile         sndfile     SNDFILE     YES   YES   "sndfile >= 1.0.28" )
 addlib( libsoxr            soxr        SOXR        YES   YES   "soxr >= 0.1.1" )
-addlib( portaudio-v19      portaudio   PORTAUDIO   YES   YES   "" )
+addlib( portaudio-v19      portaudio   PORTAUDIO   YES   YES   "portaudio-2.0" )
 addlib( sqlite             sqlite      SQLITE      YES   YES   "sqlite3 >= 3.32.0" )
 
 # Optional libraries
@@ -36,7 +36,7 @@ if (NOT USE_MIDI AND
 endif ()
 
 
-addlib( portmixer          portmixer   PORTMIXER   NO    YES   "" )
+#addlib( portmixer          portmixer   PORTMIXER   NO    YES   "" )
 if (NOT USE_PORTMIXER AND
    "EXPERIMENTAL_AUTOMATED_INPUT_LEVEL_ADJUSTMENT" IN_LIST
       EXPERIMENTAL_OPTIONS_LIST )
diff --git a/src/Experimental.cmake b/src/Experimental.cmake
index 30c01792a..ad0cc9374 100644
--- a/src/Experimental.cmake
+++ b/src/Experimental.cmake
@@ -121,7 +121,7 @@ set( EXPERIMENTAL_OPTIONS_LIST
    # RBD, 1 Sep 2008
    # Enables MIDI Output of NoteTrack (MIDI) data during playback
    # USE_MIDI must be defined in order for MIDI_OUT to work
-   MIDI_OUT
+   #MIDI_OUT
 
    # JKC, 17 Aug 2017
    # Enables the MIDI note stretching feature, which currently
```
but this fails to build:
```
../src/AudioIO.cpp: In member function ‘virtual void AudioIO::StopStream()’:
../src/AudioIO.cpp:2452:4: error: ‘mMidiPlaybackTracks’ was not declared in this scope; did you mean ‘mPlaybackTracks’?
 2452 |    mMidiPlaybackTracks.clear();
      |    ^~~~~~~~~~~~~~~~~~~
      |    mPlaybackTracks
```

### LINKED ISSUE #1186: Extract PortAudio. Update PA to the latest version
- [x] #1413
- [x] #1414
- [x]  #946
- [x] Create Conan recipe
- [x] Update dependencies list

On Windows 16bit.patch is desirable, but not strictly needed, as DSound is deprecated.

### LINKED ISSUE #1360: Jack Audio System unavailable with AppImage
**Describe the bug**
"Jack Audio System" does not appear as a "host" option when Jack is running

**To Reproduce**
1. Start Jack
2. Launch Audacity
3. Try to select "Jack Audio System" as "host" in the "Device Toolbar"
4. Observe that the only host option is "ALSA"

**Expected behavior**
"Jack Audio  System" should be available as "host" when Jack is running.

**Additional information (please complete the following information):**
 - OS: Xubuntu  20.04
 - Version: Audacity RC3 AppImage

### LINKED ISSUE #1413: Make PortMixer buildable against vanilla PortAudio
PortMixer requires a large, nontrivial patch to the PortAudio, which prevents Audacity to be buildable against the vanilla version of PortAudio,

Ubuntu and Fedora surprisingly apply it to PortAudio packages, but Arch doesn't.

The functions form the patch:

* `Pa_GetStreamHostApiType` -The host API type can just be passed to `Px_OpenMixer`

DirectSound
---

* `PaWinDS_GetStreamInputGUID`
* `PaWinDS_GetStreamOutputGUID`

Reimplementing it will be tricky. The GUID is stored in a private structure `PaWinDsDeviceInfo`.

The safest way seems to be to load `DirectSoundCaptureEnumerateW`/`DirectSoundEnumerateW` and test for the device's name (which is stored in UTF8, which poses another (simple) problem). 

WASAPI
---
* `PaWasapi_GetInputDeviceID`
* `PaWasapi_GetOutputDeviceID`

19.7.0 has added PaWasapi_GetIMMDevice

ALSA
---

The audio card id is cached. Can `snd_pcm_info_get_card` change between calls? We can cache it when `Px_OpenMixer`is called anyway. 

OSS
---

* `PaOSS_GetStreamInputDevice`
* `PaOSS_GetStreamOutputDevice`

The name can be retrieved using `Pa_GetDeviceInfo`.

### LINKED ISSUE #1414: Investigate, if WASAPI patch for PA is really needed.
Check if we need `wasapi-fix.patch` and `wasapi-loopback.patch` are still needed.

`PaWasapi_IsLoopback` is not really used by Audacity anymore, but `wasapi-loopback.patch` has other changes as well.

### PR DESCRIPTION
**Pull request by crsib**
Resolves #1186
Resolves #1413 
Resolves #1414
Resolves #871 

This PR achieves two important goals:

1. PortAudio is updated to 19.7.0
2. System PortAudio can be used. Besides Linux packaging, this is important to fix #1360

To update PortAudio, the following steps were taken:

* #946 was merged into this branch. This is required because `PaUtil_GetTime` is private, which is arguably the upstream error anyway.
* `libnyquist` and `portmixer` build systems were updated:
  * Corresponding  `CMakeLists.txt` moved into the lib-src.
  * New PortAudio target is linked to the libraries.
  * `portmixer` build system detects PortAudio capabilities.
  * Libraries were moved out of the dependencies CMakeLists.txt
  
  It is unlikely the `libnyquist` and `portmixer` will be devendored because they are very Audacity specific, so it makes sense not to treat them as 3d party dependencies, at least for not.
* `portmixer` now compiles with unmodified PortAudio. However, the full functionality on Windows requires patches to PortAudio:
  * A [patch](https://github.com/audacity/conan-recipes/blob/main/portaudio/all/patches/19.7.0/pawinmme-export.patch) to export PaWinMME_ functions, which are public, but not usable if PortAudio is built as DLL. 
  * A [patch](https://github.com/audacity/conan-recipes/blob/main/portaudio/all/patches/19.7.0/winds-getguid.patch) that allows getting the DirectSound device GUID. Without it, there was no reliable way to retrieve the GUID.
 
Additionally, there are the following patches applied to the Conan provided library:

* A [patch](https://github.com/audacity/conan-recipes/blob/main/portaudio/all/patches/19.7.0/enable-oss.patch) to enable OSS support. 
* A [patch](https://github.com/audacity/conan-recipes/blob/main/portaudio/all/patches/19.7.0/wasapi-loopback.patch) to enable WASAPI loopback devices.

One patch to PortAudio was dropped because it seemingly fixed the bug in Audacity rather than PortAudio. Also it broke `IsStreamStopped() == !IsStreamActive()` for WASAPI.

Linux [packaging scripts](https://github.com/audacity/audacity/tree/master/linux/packages) were updated, so packages are built against the system PortAudio, the results were verified on corresponding systems.

The `PortAudio devendored` commit is large because it is impossible to break it into smaller commits that compile and run, as bringing the unmodified PortAudio library as an external dependency breaks lots of stuff around.

This PR was tested with all available Host APIs on Windows and with ALSA and Jack2 on Linux. OSS, while it was verified that it is enabled - failed to me for all Linux distros I was testing against.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

File: src/DeviceManager.cpp [hunk 1]
```diff
@@ -143,7 +143,7 @@ static void AddSourcesFromStream(int deviceIndex, const PaDeviceInfo *info, std:
    FillHostDeviceInfo(&map, info, deviceIndex, 1);
 
 #ifdef USE_PORTMIXER
-   PxMixer *portMixer = Px_OpenMixer(stream, 0);
+   PxMixer *portMixer = Px_OpenMixer(stream, deviceIndex, -1, 0);
```
Comment (Paul-Licameli) [inline src/DeviceManager.cpp:146]: I stepped through this function and thought that all the complementary Px_CloseMixer calls would be nicer if done by RAII.  Put this somewhere in the C++ headers outside of PortMixer:

```
struct PortMixerDeleter{ void operator ()(void *p) { if (p) Px_CloseMixer(p); } };
using PortMixerHandle = std::unique_ptr<PxMixer, PortMixerDeleter>;
```

But that cleanup is beside the point of this PR of course.

Comment (Paul-Licameli) [reply src/DeviceManager.cpp:146]: I also now notice `#ifdef USE_PORTMIXER` in some places but `#if USE_PORTMIXER` in others, and I don't know if the distinction was intended.  Are builds with USE_PORTMIXER defined but zero really supposed to be different?

Another cleanup perhaps not for the scope of this issue.

File: lib-src/portmixer/include/portmixer.h [hunk 2]
```diff
@@ -57,7 +57,7 @@ typedef float PxBalance; /* -1.0 (left) --> 1.0 (right) */
  audio device.  Pass 0 as the index for the first (default) mixer.
 */
 
-PxMixer *Px_OpenMixer( void *pa_stream, int i );
+PxMixer* Px_OpenMixer(PaStream* pa_stream, PaDeviceIndex inputDeviceIndex, PaDeviceIndex outputDeviceIndex, int i);
```
Comment (Paul-Licameli) [inline lib-src/portmixer/include/portmixer.h:60]: I see `int i` is always zero in existing calls.  That doesn't necessarily mean the argument should be removed.  But I wonder if the generality will ever be needed, or has been tested.

Comment (Paul-Licameli) [reply lib-src/portmixer/include/portmixer.h:60]: I notice new argument names are camelCase but the library otherwise prefers snake_case for variable and member names.  Not a serious matter, just style.

File: CMakeLists.txt [hunk 3]
```diff
@@ -519,10 +519,27 @@ add_subdirectory( "cmake-proxies" )
 # Conan uses find_package and does not set GLOBAL flag
 resolve_conan_dependencies()
```
Comment (Paul-Licameli) [inline CMakeLists.txt:520]: Please explain more in the comment of this commit:
* lib-src/portmixer/portaudio.patch described how the customized portaudio used to differ from the upstream.
* Patches were motivated by needs of portmixer, but now portmixer is rewritten all in terms of the published portaudio API.
* libnyquist and portmixer, which use portaudio, also get rewrite of their build system.  (Or could this step be its own separate commit before this commit?  If so, ideally I'd do it, but verifying the rebuilds might be too bothersome now.)
* any other helpful details you think of.

Also amend the commit to delete files in lib-src/portmixer that are no longer needed: the .patch for sure, and maybe also makefiles and other relics of old build systems.  And maybe do the same for libnyquist.

**Review by Paul-Licameli — CHANGES_REQUESTED** [review]
Request to improve a commit comment and remove even more obsolete files

File: lib-src/portmixer/src/px_unix_oss.c [hunk 4]
```diff
@@ -163,15 +172,15 @@ int OpenMixer_Unix_OSS(px_mixer *Px, int index)
    info->playback.num = 0;   
    
    do {
-      info->capture.name = PaOSS_GetStreamInputDevice(Px->pa_stream);
+      info->capture.name = GetDeviceName(Px->input_device_index);
```
Comment (Paul-Licameli) [inline lib-src/portmixer/src/px_unix_oss.c:175]: I notice these are the only non-Windows usages of the new fields `input_device_index` and `output_device_index`.  They happen only in non-Apple Unices.

So what about the case of Apple?  Is it an omission that the new fields are set but not used anywhere?  Or can you reassure me you studied the problem and decided there was no need?

Comment (Paul-Licameli) [reply lib-src/portmixer/src/px_unix_oss.c:175]: I do observe now that portaudio.patch never needed anything specific to macOS, so that persuades me it's not an omission.

File: src/AudioIO.cpp [hunk 5]
```diff
@@ -488,9 +488,6 @@ time warp info and AudioIOListener and whether the playback is looped.
       #define THREAD_LATENCY 0 /* milliseconds */
    #endif
    #define ROUND(x) (int) ((x)+0.5)
-   //#include <string.h>
-//   #include "../lib-src/portmidi/pm_common/portmidi.h"
-   #include "../lib-src/portaudio-v19/src/common/pa_util.h"
```
Comment (Paul-Licameli) [inline src/AudioIO.cpp:493]: Hm, this deletion ought to be part of the previous commit by me, actually

File: src/AudioIO.cpp [hunk 6]
```diff
@@ -2398,8 +2408,14 @@ void AudioIO::StopStream()
   #endif
 
    if (mPortStreamV19) {
-      Pa_AbortStream( mPortStreamV19 );
+      // DV: Pa_CloseStream will close Pa_AbortStream internally,
+      // but it doesn't hurt to do it ourselves.
+      // PA_AbortStream will silently fail if stream is stopped.
+      if (!Pa_IsStreamStopped( mPortStreamV19 ))
+        Pa_AbortStream( mPortStreamV19 );
```
Comment (Paul-Licameli) [inline src/AudioIO.cpp:2415]: I'm not sure why these changes (justified though they may be) are a necessary part of devendoring?  I'd like to understand whether they are really independent.

**Review by Paul-Licameli — APPROVED** [review]
Let's not hold this up. I  have examined the changes in Audacity's C++ source and in PortMixer to my satisfaction.

I just suggest replicating more of the expanation of the PR comment in commit comments too, when you next rebase and force-push this.
