### PR TITLE
Fix vertical playback meter volume slider position

### LINKED ISSUE #9280: Playback volume slider isn't moving
### Bug description

_No response_

### Steps to reproduce

1. enable Playback meter
2. set its position to vertical
3. click and drag the slider
4. observe

### Expected behavior

The slider is moving along the vertical meter scale as you're dragging it.

### Actual behavior

The slider remains still, although the tooltip value is changing:

https://github.com/user-attachments/assets/55d43932-72f5-464a-9e3c-ccb4f92066c0

### Audacity Version

master

### Operating system

OS independent

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by embarc-gabriel**
Resolves: #9280 

The volume information should be updated in the meter model to calculate the slider position correctly.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:

- [ ] Autobot test cases have been run

### CODE REVIEW

File: src/playback/view/panels/playbackmeterpanelmodel.cpp [hunk 1]
```diff
@@ -7,6 +7,10 @@ using namespace au::playback;
 PlaybackMeterPanelModel::PlaybackMeterPanelModel(QObject* parent)
     : QObject(parent)
 {
+    m_meterModel = new PlaybackMeterModel(this);
+    m_meterModel->init();
```
Comment (saintmatthieu) [inline src/playback/view/panels/playbackmeterpanelmodel.cpp:15]: Better add an `init` method to this class and call `m_meterModel->init()` from inside, I think.

**Review by saintmatthieu — APPROVED** [review]

File: src/playback/view/panels/playbackmeterpanelmodel.cpp (hunk 1 above)
Comment (embarc-gabriel) [reply src/playback/view/panels/playbackmeterpanelmodel.cpp:15]: Fixed.
