### PR TITLE
Clips can't be dragged past the topmost track

### LINKED ISSUE #8451: Freeze when Shift+Dragging Clips across Timeline Vertically
### Bug description

If the User selects multiple clips via shift, and then moves them along the timeline vertically, Audacity will freeze. 

### Steps to reproduce

1. Launch Audacity 4 
2. Generate multiple clips 
3. Shift Select clips
4. Move them around vertically by grabbing the bottom one
5. Observe Result

### Expected behavior

Audacity shouldn't freeze. 	

### Actual behavior

Audacity freezes. 

### Audacity Version

a6c70af65f94915ce750fdaab49435012d0591a3

### Operating system

OS Independent

### Additional context

https://github.com/user-attachments/assets/b07ec036-f39b-4e3f-b3b5-1650600d7389

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #8451

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by grliszas14 — APPROVED** [review]

File: src/trackedit/internal/au3/au3interactionutils.h [hunk 1]
```diff
@@ -39,7 +39,15 @@ au3::Au3WaveTrack* toggleStereo(au3::Au3TrackList& tracks, size_t trackIndex);
 au3::Au3WaveTrack* appendWaveTrack(au3::Au3TrackList& tracks, size_t nChannels, const au3::Au3WaveTrackFactory* trackFactory = nullptr,
                                    double projectRate = 0.);
 
-NeedsDownmixing moveClipsUpOrDown(int offset, const au3::Au3TrackList& orig, au3::Au3TrackList& copy,
+enum class UpOrDown {
```
Comment (Eism) [inline src/trackedit/internal/au3/au3interactionutils.h:42]: or more abstract name MoveDirection?

File: src/trackedit/internal/au3/au3interactionutils.h [hunk 2]
```diff
@@ -39,7 +39,15 @@ au3::Au3WaveTrack* toggleStereo(au3::Au3TrackList& tracks, size_t trackIndex);
...
+    Up,
+    Down
+};
+
+/*!
+ * @pre `upOrDown == UpOrDown::Down` or track indices of selected clips are not 0 (i.e. can't drag clips up past the topmost track)
+ */
+NeedsDownmixing moveClipsUpOrDown(UpOrDown upOrDown, const au3::Au3TrackList& orig, au3::Au3TrackList& copy,
```
Comment (Eism) [inline src/trackedit/internal/au3/au3interactionutils.h:50]: or moveClipsVertical

File: src/trackedit/internal/au3/au3interactionutils.h (hunk 1 above)
Comment (saintmatthieu) [reply src/trackedit/internal/au3/au3interactionutils.h]: `MoveDirection` no, because it's specifically for up or down. But I agree the name is ugly. I pushed something I think is better.
