### PR TITLE
7769 generator b&m format fixes

### LINKED ISSUE #7769: Generator Time Length Values are Corrupted
### Bug description

If the User enters values in 'bars:beats' mode for the length of a tone for the tone generator, then later changes the mode of the length (time format), the value will become corrupted. Also, no changes are reflected in bar:beat modes. 

### Steps to reproduce

1. Launch Audacity
2. Create Mono/Stereo Track
3. Open Tone Generator
4. Switch to bar:beat or bar:beat:tick
5. Input any value
6. Observe no values being registered
7. Switch duration mode to any other than 'bar:beat:tick' or 'bar:beat'
8. Observe

### Expected behavior

The User should be able to enter values in bar:beat modes. 

### Actual behavior

The User is not be able to enter values in bar:beat modes. 

https://github.com/user-attachments/assets/9dc2c739-9594-47f7-8e02-223cda01f9af

### Audacity Version

Audacity 4 alpha

### Operating system

Windows

### Additional context

This is reproducible on the original AU4 tone generator PR: https://github.com/audacity/audacity/actions/runs/11720272206

### LINKED ISSUE #7859: Tone generator: duration issues
1. In tone generator, the default duration value is `00h00m00s`
2. The default duration format is `hh:mm:ss` when there's a point selection
3. Digits cannot be entered into the duration text box. Entering from the keyboard simply iterates from one digit to another. DTMF generator has the same problem.

Expected:
1. the default duration value of `00h00m30s`
2. the default duration format `hh:mm:ss+milliseconds` when there's a point selection
3. digits are allowed to be entered

image

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #7769 
Resolves: #7859

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:
- [ ] Also test that the equivalent widget in the playback toolbar still works properly.

### CODE REVIEW

File: src/playback/view/toolbars/components/timecodemodel.h [hunk 1]
```diff
@@ -16,10 +16,10 @@ class TimecodeModel : public QAbstractListModel
 
     Q_PROPERTY(double value READ value WRITE setValue NOTIFY valueChanged FINAL)
 
-    Q_PROPERTY(double sampleRate READ sampleRate WRITE setSampleRate NOTIFY sampleRateChanged FINAL)
-    Q_PROPERTY(double tempo READ tempo WRITE setTempo NOTIFY tempoChanged FINAL)
-    Q_PROPERTY(int upperTimeSignature READ upperTimeSignature WRITE setUpperTimeSignature NOTIFY upperTimeSignatureChanged FINAL)
-    Q_PROPERTY(int lowerTimeSignature READ lowerTimeSignature WRITE setLowerTimeSignature NOTIFY lowerTimeSignatureChanged FINAL)
+    Q_PROPERTY(double sampleRate READ sampleRate WRITE setSampleRate FINAL)
```
Comment (saintmatthieu) [inline src/playback/view/toolbars/components/timecodemodel.h:19]: I reckon that these notifications aren't necessary and even confusing, since in fact this class won't change these values from the inside.
I was also wondering: is there a need for the `READ sampleRate` ? I tried without and it seemed to work (but since this seems harmless I left them).

File: src/playback/qml/Audacity/Playback/components/Timecode.qml [hunk 2]
```diff
@@ -15,10 +15,10 @@ RowLayout {
 
     property alias value: timecodeModel.value
 
-    property alias sampleRate: timecodeModel.sampleRate
-    property alias tempo: timecodeModel.tempo
-    property alias upperTimeSignature: timecodeModel.upperTimeSignature
-    property alias lowerTimeSignature: timecodeModel.lowerTimeSignature
+    property real sampleRate
```
Comment (Eism) [inline src/playback/qml/Audacity/Playback/components/Timecode.qml:18]: hmm, is this necessary?

File: src/effects/builtin/common/generatoreffectmodel.h [hunk 3]
```diff
@@ -14,23 +14,33 @@ class GeneratorEffectModel : public AbstractEffectModel
...
+    void tempoChanged();
+    void upperTimeSignatureChanged();
+    void lowerTimeSignatureChanged();
     void durationChanged();
     void durationFormatChanged();
 
 private:
-    void doReload() override;
+    void doReload() final override;
+    virtual void doEmitSignals() = 0;
```
Comment (Eism) [inline src/effects/builtin/common/generatoreffectmodel.h:43]: Could you explain why we need another method?

File: src/effects/builtin/common/generatoreffect.h [hunk 4]
```diff
@@ -3,17 +3,27 @@
  */
 #pragma once
 
+#include "context/iglobalcontext.h"
+#include "playback/iplayback.h"
+#include "modularity/ioc.h"
```
Comment (Eism) [inline src/effects/builtin/common/generatoreffect.h:8]: please move it to the top

File: src/playback/view/toolbars/components/timecodemodel.cpp [hunk 5]
```diff
@@ -238,20 +238,9 @@ void TimecodeModel::updateValueString()
     constexpr auto toNearest = true;
     QString newValueString = m_formatter->valueToString(m_value, toNearest).valueString;
 
-    if (newValueString.size() != m_valueString.size()) {
```
Comment (Eism) [inline src/playback/view/toolbars/components/timecodemodel.cpp:241]: the component works as expected on the main toolbar? please check it

File: src/playback/qml/Audacity/Playback/components/Timecode.qml (hunk 2 above)
Comment (saintmatthieu) [reply src/playback/qml/Audacity/Playback/components/Timecode.qml:18]: Indeed they are not. Thanks!

File: src/effects/builtin/common/generatoreffect.h (hunk 4 above)
Comment (saintmatthieu) [reply src/effects/builtin/common/generatoreffect.h:8]: Why ?

File: src/playback/view/toolbars/components/timecodemodel.cpp (hunk 5 above)
Comment (saintmatthieu) [reply src/playback/view/toolbars/components/timecodemodel.cpp:241]: It does now. On your latest master, select the `hh:mm:ss + milliseconds` format, and then change to `bar:beat:tick`.

File: src/effects/builtin/common/generatoreffectmodel.h (hunk 3 above)
Comment (Eism) [reply src/effects/builtin/common/generatoreffectmodel.h:43]: what if we want to add some logic to doReload that is different from sending signals?
there is a high probability that we will add this, then we will revert your change?

File: src/playback/view/toolbars/components/timecodemodel.cpp (hunk 5 above)
Comment (Eism) [reply src/playback/view/toolbars/components/timecodemodel.cpp:241]: for qa

File: src/effects/builtin/common/generatoreffectmodel.h (hunk 3 above)
Comment (saintmatthieu) [reply src/effects/builtin/common/generatoreffectmodel.h:43]: I don't understand your concern. If `GeneratorEffectModel::doReload()` needs to do yet something else, then it does something else, and still call `doEmitSignals()`.

File: src/effects/builtin/common/generatoreffect.h (hunk 4 above)
Comment (saintmatthieu) [reply src/effects/builtin/common/generatoreffect.h:8]: But certainly, a header file should not rely on other header files being included before itself, right ?
And order of importance: I don't know what that is and I don't want to spend time thinking about it when I include.

Comment (Eism) [reply src/effects/builtin/common/generatoreffect.h:8]: it's more about code cleanliness

**Review by Eism — APPROVED** [review]
