### PR TITLE
[Au4] project_actions: formatted the text in a new project close dialog.

### LINKED ISSUE #10631: Wrong filename and path when in the save dialog when quitting Audacity
1. New project
2. Quit Audacity
3. Observe: the path shown in the dialog is and the path is `\Users\<username>\AppData\Local\Audacity\Audacity4\SessionData\New project <yyyy-mm-dd hh-mm-ss> N-1.aup4unsaved` whereas it should be `Untitled.aup4`

### Windows (full path is displayed):

Image

### MacOS (only the name is displayed):

Image

### Expected result:

Image

### PR DESCRIPTION
**Pull request by PawBud**
Resolves: #10631

The quit dialog of a new project now displays "Do you want to save changes to the project before closing?"

Screenshot 2026-04-03 at 13 23 40

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

Tested on macOS (26.4 (25E246))

QA:

- [ ] Autobot test cases have been run

### CODE REVIEW

**Comment by PawBud** [comment]
The code feels hacky. I went through Audactiy's [styleguide](https://audacity.gitbook.io/dev/getting-started/coding-standards).

kindly let me know what I can correct.

Update: fixing styling issues.

**Comment by PawBud** [comment]
> ♻️ Duplicate comments (1)
> 
> > src/project/internal/projectactionscontroller.cpp (1)> `640-646`: _⚠️ Potential issue_ | _🟠 Major_
> > > **Unsaved-project detection is tied to `displayName()` and can miss the intended branch.**
> > > At **Line 640** / **Line 641**, deriving unsaved state from `project->displayName()` plus suffix `"aup4unsaved"` is brittle and likely false for new projects (UI name often has no such suffix). This can prevent the new generic dialog text from appearing when it should.
> > > 
> > > Suggested fix
> > > ```diff
> > > -    muse::io::path_t displayName = project->displayName();
> > > -    if (muse::io::suffix(displayName) == "aup4unsaved") {
> > > +    const bool isUnsavedSessionProject = project->isNewlyCreated()
> > > +                                         || muse::io::suffix(project->path()) == "aup4unsaved";
> > > +    if (isUnsavedSessionProject) {
> > >          title = muse::qtrc("project", "Do you want to save changes to the project before closing?").toStdString();
> > >      } else {
> > >          title = muse::qtrc("project", "Do you want to save changes to the project “%1” before closing?")
> > >                  .arg(project->displayName()).toStdString();
> > >      }
> > > ```
> 
> ℹ️ Review info
> ⚙️ Run configuration
> 
> 📥 Commits
> 
> 📒 Files selected for processing (1)

regarding this, I took inspiration from [here](https://github.com/audacity/audacity/blob/4cdebd1fd3318583b14d2e667a202aee5a0515c3/src/importexport/export/view/exportpreferencesmodel.cpp#L95)

File: src/project/internal/projectactionscontroller.cpp [hunk 1]
```diff
@@ -635,8 +635,15 @@ muse::io::paths_t ProjectActionsController::selectImportFiles()
...
-                        .arg(project->displayName()).toStdString();
+    std::string title;
+
+    muse::io::path_t displayName = project->displayName();
+    if (muse::io::suffix(displayName) == "aup4unsaved") {
+        title = muse::qtrc("project", "Do you want to save changes to the project before closing?").toStdString();
+    } else {
+        title = muse::qtrc("project", "Do you want to save changes to the project “%1” before closing?")
+                .arg(project->displayName()).toStdString();
+    }
```
Comment (saintmatthieu) [inline src/project/internal/projectactionscontroller.cpp:646]: Hi @PawBud , thanks a lot for your contribution!

The solution you propose is fragile: if we change at some stage the suffix of unsaved projects, it will reintroduce this bug without us noticing.

The `IAudacityProject` interface has a `isNewlyCreated()` method that I think is suitable. I suggest we use it, e.g.

```cpp
    std::string title;
    if (!project->isNewlyCreated()) {
        title = muse::qtrc("project", "Do you want to save changes to the project “%1” before closing?")
                .arg(project->displayName()).toStdString();
    } else {
        title = muse::trc("project", "Do you want to save changes to the project before closing?");
    }
```

**Review by saintmatthieu — CHANGES_REQUESTED** [review]
Please consider using my suggestion or let me know why not.

File: src/project/internal/projectactionscontroller.cpp (hunk 1 above)
Comment (saintmatthieu) [reply src/project/internal/projectactionscontroller.cpp:646]: I notice that the bot suggests the same: https://github.com/audacity/audacity/pull/10659#pullrequestreview-4055362379

Comment (PawBud) [reply src/project/internal/projectactionscontroller.cpp:645]: sounds good, will update it accordingly. Thanks for reviewing it :)

**Comment by PawBud** [comment]
> Please consider using my suggestion or let me know why not.

Seems like a good idea, updated as requested :)

**Review by saintmatthieu — APPROVED** [review]

**Comment by saintmatthieu** [comment]
@PawBud thanks a lot once more :)
