### PR TITLE
VST3 realtime effects: force setting commit when closing dialog

### LINKED ISSUE #8640: VST effect's parameters aren't remembered in the Realtime Effects panel
### Bug description

_No response_

### Steps to reproduce

1. Add a VST plugin to the realtime effects stack
2. Tweak some parameters
3. Close its GUI
4. Open it
5. Check the parameters

### Expected behavior

The parameters remain the same as you've set them.

### Actual behavior

The parameters got reset to default.

https://github.com/user-attachments/assets/e32ae73e-6087-4b20-b096-15f783a93c0b

### Audacity Version

master

### Operating system

OS independent

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #8640

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: src/effects/vst/view/vstviewmodel.cpp [hunk 1]
```diff
@@ -56,31 +57,35 @@ void VstViewModel::init()
 
     settingsToView();
 
-    QObject::connect(&m_settingUpdateTimer, &QTimer::timeout, this, &VstViewModel::checkSettingChangesFromUi);
+    QObject::connect(&m_settingUpdateTimer, &QTimer::timeout, this, &VstViewModel::checkSettingChangesFromUiWhileIdle);
```
Comment (kryksyh) [inline src/effects/vst/view/vstviewmodel.cpp:60]: VstViewModel is a QObject, so there is no need to explicitly call for 
> QObject::connect

File: src/effects/vst/view/vstviewmodel.cpp [hunk 2]
```diff
@@ -56,31 +57,35 @@ void VstViewModel::init()
...
         wrapper.FlushParameters(settings, &hasChanges);
-        if (hasChanges) {
+        if (hasChanges || forceCommitting) {
             wrapper.StoreSettings(settings);
         }
         return nullptr;
     });
 
-    if (hasChanges) {
+    if (hasChanges || forceCommitting) {
```
Comment (kryksyh) [inline src/effects/vst/view/vstviewmodel.cpp:88]: Why do we need to force committing in destructor if there are no changes?

**Review by kryksyh — APPROVED** [review]

File: src/effects/vst/view/vstviewmodel.cpp (hunk 2 above)
Comment (saintmatthieu) [reply src/effects/vst/view/vstviewmodel.cpp:88]: There may or may not be changes, but if these happened during playback, for some reason I haven't investigated, `hasChanges` never gets set to `true`.
I stupidly replicated the behavior in Audacity 3, which calls `StoreSettings` on dialog close.

File: src/effects/vst/view/vstviewmodel.cpp (hunk 1 above)
Comment (saintmatthieu) [reply src/effects/vst/view/vstviewmodel.cpp:60]: Yeah, sure. On the other hand, it is a static method, so I don't think it harms intelligibility either.
