### PR TITLE
Fix #10582. Drag and drop import uses project sample rate

### LINKED ISSUE #10582: Drag and drop import does not use file sample rate
### Bug description

When importing a file by dragging and dropping it into a new track, the new track will use the project sample rate instead of the imported file sample rate. Importing using File > Import correctly uses the file sample rate.

### Steps to reproduce

1. Generate an audio file with 44.1kHz sample rate
2. Create a new blank project
3. Set the project sample rate to 48kHz
4. Drag and drop the 44.1kHz file into a new track

### Expected behavior

New track created when importing a file by dragging and dropping should use the file sample rate, not the project sample rate.

### Actual behavior

The new track sample rate will be incorrectly set to 48kHz
Specific sample rates used for project/file sample rates are not important. Behavior is consistent with different sample rates

Image

### Audacity Version

e9ba3fa1f7ff8988ad86cdee45431355a35869cf

### Operating system

Windows

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by loudifier**
… rate

Resolves: [#10582](https://github.com/audacity/audacity/issues/10582)

Importing a file by dragging and dropping creates a new track and sets the track sample rate to the project sample rate instead of the file sample rate.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR
- [x ] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:

- [ ] Autobot test cases have been run

### CODE REVIEW

File: src/trackedit/internal/au3/au3tracksinteraction.cpp [hunk 1]
```diff
@@ -292,10 +292,18 @@ muse::Ret Au3TracksInteraction::pasteClips(const std::vector<Au3TrackDataPtr>& c
...
+            // For empty tracks, adopt the sample rate from the imported audio
+            if (dstWaveTrack->GetRate() != trackToPaste->GetRate()) {
+                dstWaveTrack->SetRate(trackToPaste->GetRate());
+                prj->trackChanged().send(DomConverter::track(dstWaveTrack));
+            }
+            // Handle channel mismatch
+            if (trackToPaste->NChannels() != dstWaveTrack->NChannels()) {
+                auto& trackList = au3::Au3TrackList::Get(projectRef());
+                dstWaveTrack = utils::toggleStereo(trackList, *dstWaveTrack);
+                prj->trackChanged().send(DomConverter::track(dstWaveTrack));
```
Comment (embarc-gabriel) [inline src/trackedit/internal/au3/au3tracksinteraction.cpp:309]: Hey @loudifier ! Can you modify the code to avoid sending trackChanged twice when both the channel and the rate are the same?

Comment (loudifier) [reply src/trackedit/internal/au3/au3tracksinteraction.cpp:309]: Yes, fixed to only call it once

**Comment by embarc-gabriel** [comment]
@dozzzzer, do you need to test it, or can I go ahead and merge it?

**Comment by dozzzzer** [comment]
@embarc-gabriel I'd test it for sure :)
