### PR TITLE
Avoid crash while clicking on the timeline

### LINKED ISSUE #9890: Clicking multiple times on the timeline crashes the app on debug mode
### Bug description

Clicking multiple times on the timeline crashes the app if on debug mode.

### Steps to reproduce

1. Open the app
2. Create some audio
3. Click on the timeline
4. Click on the clip
5 . Repeate 3 and 4

### Expected behavior

No crash

### Actual behavior

App crashes.

### Audacity Version

master

### Operating system

OS independent

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by embarc-gabriel**
Resolves: #9890 

Clicking on the timeline multiple times crashes the app.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:

- [ ] Autobot test cases have been run

### CODE REVIEW

File: src/projectscene/view/timeline/playregioncontroller.cpp [hunk 1]
```diff
@@ -65,7 +65,7 @@ void PlayRegionController::startInteraction(double pos, bool ctrlPressed)
 
     uicontextResolver()->currentUiContextChanged().onNotify(this, [this]() {
         finishInteraction(m_dragStartPos);
-    });
+    }, muse::async::Asyncable::Mode::SetReplace);
```
Comment (kryksyh) [inline src/projectscene/view/timeline/playregioncontroller.cpp]: I believe it will be better to move this and conect to `init` function

Comment (embarc-gabriel) [reply src/projectscene/view/timeline/playregioncontroller.cpp]: @kryksyh fixed

**Review by kryksyh — APPROVED** [review]
