### PR TITLE
8183 vst3 realtime support

### LINKED ISSUE #8183: VST3 realtime support
### Description

The support of VST effects in the context of destructive effects was merged.
This is not yet functional with realtime effects, though.

One of the main "challenges" of this task is to get the `RealtimeEffectViewerDialog.qml` the possibility of having a VST viewer injected, or VST and built-in effect viewers must be unified. (Those are the options I see at the moment.)

Another problem: I crash AU4 if I selected e.g. MuseHub's Chorus as realtime effect. (Not sure if it's realtime-effect-specific.)

Also, a one-liner is needed to make VSTs recognized as realtime-capable effects:
Image
But this one-liner must only be merged after VSTs work as realtime effects, too ; better no realtime VSTs than broken VSTs.

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #8183

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: src/effects/effects_base/view/effectviewloader.cpp [hunk 1]
```diff
@@ -33,9 +37,20 @@ EffectViewLoader::EffectViewLoader(QObject* parent)
     : QObject(parent)
 {}
 
-void EffectViewLoader::load(const QString& type, const QString& instanceId, const QString& effectState, QObject* itemParent)
+void EffectViewLoader::load(const QString& instanceId, QObject* itemParent)
 {
-    LOGD() << "type: " << type << ", instanceId: " << instanceId;
+    LOGD() << "instanceId: " << instanceId;
+
+    // TODO: could instancesRegister have a `typeByInstanceId` method?
```
Comment (IliasBergstromMuse) [inline src/effects/effects_base/view/effectviewloader.cpp:44]: Minor point: Generally I only merge TODO's if they correspond clearly to a ticket which directly links to them, otherwise they're easily forgotten.

File: src/effects/vst3-realtime-support.md
Comment (IliasBergstromMuse) [inline src/effects/vst3-realtime-support.md:1]: A suggestion - it is common that .md docs on design and architecture among other things, are organized in /docs in the repo. Maybe move this to /docs, and we can start collecting all things like this there?

**Comment by IliasBergstromMuse** [comment]
Thanks also for explaining this!

It reads well and the design is sound. Might be worth reducing the .qml duplication for the two different effect dialog types since they're largely identical - as we discussed, in a future PR, not necessarily this one!

**Review by IliasBergstromMuse — APPROVED** [review]

File: src/app/main.cpp [hunk 2]
```diff
@@ -160,6 +162,8 @@ int main(int argc, char** argv)
 #endif
 #ifdef AU_MODULE_EFFECTS_VST
     app.addModule(new au::effects::VstEffectsModule());
+#else
+    app.addModule(new au::effects::VstEffectsStubModule());
```
Comment (Eism) [inline src/app/main.cpp:166]: usually, we use the same name for stubs, this will simplify the code a little

Comment (saintmatthieu) [reply src/app/main.cpp:166]: Didn't think of this. From your experience, doesn't it make code navigation sometimes tricky, though ?
