### PR TITLE
fix: Handle 32bit FLAC files

### LINKED ISSUE #6606: Error on opening 32-bit FLAC
### Bug description

32-bit support is added to [FLAC v1.4.0](https://xiph.org/flac/2022/09/09/flac-1-4-0-released.html).

And it seems like Audacity cannot handle 32-bit FLAC. (import / export)

### Steps to reproduce

Open a 32-bit FLAC encoded file.

[M1F1-int32WE-AFsp.zip](https://github.com/user-attachments/files/15566749/M1F1-int32WE-AFsp.zip)
This zip contains the 32-bit FLAC to test and 32-bit WAV to compare.

### Expected behavior

img1
Expected to open normally like WAV on 1st track.

### Actual behavior

Opened FLAC has incorrect scale like on 2nd track. (without FFmpeg)

Opened FLAC is empty. (with FFmpeg)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kdm9**
Thanks for all your work such a fantastic tool!

This PR resurrects & extends #6638, to solve #6606, namely the inappropriate conversion of 32bit PCM FLAC files to floating point tracks.

We handle this by promoting 24/32bit FLAC files to floating point tracks, doing the int->float during import of each frame.

This fixes #6606 for me, though I am still testing on more sample data, and comparing to external conversion with ffmpeg to check.

This should port pretty nicely to AU4, so once you are happy with this I can make a separate PR for AU4/main branch.

Resolves: #6606 

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by LWinterberg** [comment]
Ohey, so my thinking wasn't entirely wrong!

File: modules/import-export/mod-flac/ImportFLAC.cpp [hunk 1]
```diff
@@ -243,10 +242,16 @@ FLAC__StreamDecoderWriteStatus MyFLACFile::write_callback(const FLAC__Frame *fra
                      int16Sample);
          }
          else {
-            channel.AppendBuffer((samplePtr)buffer[chn],
-                     int24Sample,
+            auto tmp = ArrayOf<float>{ frame->header.blocksize };
+            // handles both 24/32bit PCM. Divide by 2^n-1 to form -1-1 scaled floats
```
Comment (kryksyh) [inline modules/import-export/mod-flac/ImportFLAC.cpp]: @kdm9 is there a specific reason you chose to convert 24bit to float?

Comment (kdm9) [reply modules/import-export/mod-flac/ImportFLAC.cpp]: I guess not, I've reverted this in the latest commit.

**Review by kryksyh — APPROVED** [review]
