### PR TITLE
Execute bound checking before accessing vector

### LINKED ISSUE #7992: Double-clicking in the blank area of the project causes a crash
image

OS: Any

### PR DESCRIPTION
**Pull request by embarc-gabriel**
Resolves: #7992 

Very simple PR to avoid crashing while accessing first position of an empty vector.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: src/projectscene/view/clipsview/selectionviewcontroller.cpp [hunk 1]
```diff
@@ -186,6 +186,11 @@ void SelectionViewController::selectTrackAudioData(double y)
     }
 
     const std::vector<TrackId> tracks = determinateTracks(m_startPoint.y(), y);
+    if (tracks.empty())
+    {
```
Comment (grliszas14) [inline src/projectscene/view/clipsview/selectionviewcontroller.cpp:190]: I think we should have opening bracket in the previous line according to our code style guidelines

**Review by grliszas14 — APPROVED** [review]

**Review by kryksyh — APPROVED** [review]

File: src/projectscene/view/clipsview/selectionviewcontroller.cpp (hunk 1 above)
Comment (embarc-gabriel) [reply src/projectscene/view/clipsview/selectionviewcontroller.cpp:190]: Oh yes! I have format on save enabled. Should it automatically format it?

Comment (embarc-gabriel) [reply src/projectscene/view/clipsview/selectionviewcontroller.cpp]: @kryksyh @grliszas14 fixed.

Comment (embarc-gabriel) [reply src/projectscene/view/clipsview/selectionviewcontroller.cpp]: Ahhh the clang PR was not merged yet.

**Review by saintmatthieu — APPROVED** [review]
