### PR TITLE
5548 parse audio file title for loop metadata

### LINKED ISSUE #5548: Parse audio file title for loop metadata
Goal is to add a follow-up attempt if #5546 fails to gather useful metadata. This ticket should probably wait for #5546 to be complete so as to re-use whatever C++ struct came out of it and try to fill it.

We don't have prior knowledge of standard encoding of such information in audio file title, hence this ticket entails a part of research.

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #5548

Introduce `lib-music-information-retrieval` with its filename parsing and integrate it into the import workflow.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes in behavior

### New preference
- [x] There is a new section in the `Import / Export` preferences. Its values match the pop-up dialog mentioned below, and using the "Don't ask me again" checkbox in the pop-up modifies the value in the preferences accordingly.
- [x] By default, it has the value "Ask me each time".

### Regular expression

The regex may be (more or less correctly) summarized as `<(anything + (directory) separator) or nothing> <integer from 30 to 300 inclusive> <separator or nothing> <bpm (case-insensitive)> <separator or nothing>`. In case that helps, here is the current list of test cases:
```cpp
      { "120 BPM", 120 },

      // it is case-insensitive
      { "120 Bpm", 120 },

      // there may be an extension
      { "120 BPM.opus", 120 },

      // it may be preceeded by a path
      { "C:/my\\path/to\\120 BPM", 120 },

      // value must be between 30 and 300 inclusive
      { "1 BPM", std::nullopt },
      { "29 BPM", std::nullopt },
      { "30 BPM", 30 },
      { "300 BPM", 300 },
      { "301 BPM", std::nullopt },
      { "1000 BPM", std::nullopt },

      // it may be preceeded by zeros
      { "000120 BPM", 120 },

      // there may be something before the value
      { "anything 120 BPM", 120 },
      // but then there must be a separator
      { "anything120 BPM", std::nullopt },
      // there may be something after the value
      { "120 BPM anything", 120 },
      // but then there must also be a separator
      { "120 BPManything", std::nullopt },

      // what separator is used doesn't matter
      { "anything-120-BPM", 120 },
      { "anything_120_BPM", 120 },
      { "anything.120.BPM", 120 },

      // but of course that can't be an illegal filename character
      { "120/BPM", std::nullopt },
      { "120\\BPM", std::nullopt },
      { "120:BPM", std::nullopt },
      { "120;BPM", std::nullopt },
      { "120'BPM", std::nullopt },
      // ... and so on.

      // separators before and after don't have to match
      { "anything_120-BPM", 120 },

      // no separator between value and "bpm" is ok
      { "anything.120BPM", 120 },

      // a few real file names found out there
      { "Cymatics - Cyclone Top Drum Loop 3 - 174 BPM", 174 },
      { "Fantasie Impromptu Op. 66.mp3", std::nullopt },
```
#### Importing with "Ask me each time"

The user has their pref set to "Ask me each time",
- [x] importing on empty project launches user prompt
- [x] importing on a non-empty project, if the view is in minutes and seconds, nothing happens
- [x] importing on non-empty project, if the view is in beats and measures, clip is auto-stretched, and Ctrl-Z undoes import

#### Interacting with modal

The project is empty, the user hasn't already recorded their preference by checking "Don't ask again", and imports a file with BPM in its title. The prompt appears.

-  [x] If a user says "No", auto-stretches if in B&M mode, else nothing happens. Ctrl-Z undoes import.
-  [x] If a user says "Yes", the view switches to Beats-and-measures if not already there, and the project tempo becomes that of the clip. Ctrl-Z undoes only project configuration, without stretching the clip.

#### Persistency

- [x] The user recorded their preference by checking "Don't ask again". They now drop an audio file with BPM information in its title. Audacity behaves as described in this table:

| Case | Pref         | View is Beats and Measures | Project is empty | Result                                     |
| ---- | ------------ | -------------------------- | ---------------- | ------------------------------------------ |
| A    | "Do nothing" | No                         | Yes              | Nothing                                    |
| B    | "Do nothing" | No                         | No               | Nothing                                    |
| C    | "Do nothing" | Yes                        | Yes              | auto-stretch                               |
| D    | "Do nothing" | Yes                        | No               | auto-stretch                               |
| E    | "Switch ..." | No                         | Yes              | Switch to B&M and project takes clip tempo |
| F    | "Switch ..." | No                         | No               | Nothing                                    |
| G    | "Switch ..." | Yes                        | Yes              | project takes clip tempo                   |
| H    | "Switch ..." | Yes                        | No               | auto-stretch                               |

#### Miscellaneous
- [x] Applying macro to file(s) still works (cf. https://github.com/audacity/audacity/issues/5604)
- [x] Importing file without BPM info in file name behaves as before
- [x] The prompt can be tab-traversed, has all buttons functional, and the close button as well as ESC are equivalent to "No".
- [x] Answering "Yes" to the prompt adds a history item, and can be undone from the `Edit` menu or with ctrl-Z. Undoing means reverting to the previous tempo and view.
- [x] The amount of stretching is minimized through power-of-two speed changes. E.g., if a clip with title BPM 50 is dropped in a project with tempo 90, the clip is auto-stretched to 45 BPM, i.e., its speed is set to 90% rather than 180%.
- [x] For loops lasting _N_ quarter notes + _e_, with _e_ less than a 32nd, _e_ is trimmed off from the right (to ease horizontally duplicating loops)
- [x] Pressing the left or right arrow with some clip selected and snap enabled now snaps the resulting position. (That's an important one, ask if it's unclear, which it probably is.)
- [x] If you have audio files with numbers in their name that you think might be misinterpreted as tempo, please try them out. Likewise, if you have audio files with tempo in their name they don't get recognized. Any misinterpretation please share the file name with me so that I can improve my regex with it. Thank you.
- [x] Importing more than one file at once behaves like it did before - no stretching, no project re-configuration.

### CODE REVIEW

File: src/prefs/MusicInformationRetrievalPrefs.cpp [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#include "MusicInformationRetrievalPrefs.h"
+
+ChoiceSetting UseMirResultToConfigureProject {
+   wxT("/GUI/UseMirResultToConfigureProject"),
+   { ByColumns,
+     { {}, {}, {} },
+     { wxString("Yes"), wxString("No"), wxString("Ask") } },
```
Comment (vsverchinsky) [inline src/prefs/MusicInformationRetrievalPrefs.cpp:7]: Shouldn't be there a way to change that in preferences dialog?

File: src/ProjectFileManager.cpp [hunk 2]
```diff
@@ -1036,12 +1041,12 @@ void ProjectFileManager::FixTracks(TrackList& tracks,
                RealtimeEffectList::Get(*right).Clear();
 
                if(left->GetRate() != right->GetRate())
-                  //i18n-hint: explains why opened project was auto-modified 
+                  //i18n-hint: explains why opened project was auto-modified
                   onUnlink(XO("This project contained stereo tracks with different sample rates per channel."));
                if(left->GetSampleFormat() != right->GetSampleFormat())
-                  //i18n-hint: explains why opened project was auto-modified  
+                  //i18n-hint: explains why opened project was auto-modified
```
Comment (vsverchinsky) [inline src/ProjectFileManager.cpp:1047]: This file has too many whitespace changes

File: src/ProjectFileManager.cpp [hunk 3]
```diff
@@ -16,53 +16,58 @@ Paul Licameli split from AudacityProject.cpp
...
 #include "import/ImportMIDI.h"
 #include "import/ImportStreamDialog.h"
+#include "prefs/MusicInformationRetrievalPrefs.h"
 #include "toolbars/SelectionBar.h"
-#include "AudacityMessageBox.h"
+#include "tracks/playabletrack/wavetrack/WaveTrackUtils.h"
 #include "widgets/FileHistory.h"
 #include "widgets/UnwritableLocationErrorDialog.h"
 #include "widgets/Warning.h"
+#include "wxFileNameWrapper.h"
```
Comment (vsverchinsky) [inline src/ProjectFileManager.cpp:65]: And `#include` reorderings...

File: src/ProjectFileManager.cpp [hunk 4]
```diff
@@ -1311,15 +1316,108 @@ class ImportProgress final
...
+}
 
+bool UserWantsMirResultToConfigureProject(AudacityProject& project)
+{
+   const auto policy = UseMirResultToConfigureProject.Read();
+   if (policy == wxString("Ask"))
+   {
+      AudacityDontAskAgainMessageDialog m(
+         &GetProjectPanel(project), XO("Import"),
+         XO("Use detected music information to configure project?"));
```
Comment (vsverchinsky) [inline src/ProjectFileManager.cpp:1345]: Shouldn't we display detected bpm value in that dialog, to make user well informed about the choice?

Btw, I get strange results when trying to import "Big Bass Hit" from MuseHub. It sets my project tempo to 542,373

File: libraries/lib-wx-wrappers/SpinControl.cpp [hunk 5]
```diff
@@ -339,8 +339,13 @@ void SpinControl::SetValue(double value, bool silent)
...
    value = std::clamp(value, mMinValue, mMaxValue);
 
-   // Should some epsilon be used here?
-   if (value == mValue)
+   // `value` may be the text readout of `mTextControl`, whose difference with
+   // the actual stored `mValue` can be greater than 0.001. Even such a small
+   // delta between project tempo and clip raw audio tempo can yield a tiny
+   // speed change, e.g. 100.1%, which is upsetting. This is an imperfect
+   // workaround. Better ideas welcome.
+   constexpr auto epsilon = 0.002;
```
Comment (vsverchinsky) [inline libraries/lib-wx-wrappers/SpinControl.cpp:347]: `constexpr auto epsilon = std::numeric_limits<double>::epsilon() * mStep`?

File: src/ProjectFileManager.cpp (hunk 4 above)
Comment (saintmatthieu) [reply src/ProjectFileManager.cpp:1345]: Yo, me too. I messed up a constant during clean-up, fix in 6c471cd.

File: libraries/lib-music-information-retrieval/.clang-format [hunk 6]
```diff
@@ -0,0 +1,40 @@
+AccessModifierOffset: '-3'
```
[the remark this answers is not in the document]
Comment (saintmatthieu) [reply libraries/lib-music-information-retrieval/.clang-format:1]: I want all chances on this library's side that it stays well formatted. But maybe it's time to check in this .clang-format in the root of the repo - I don't know of an automation that would want to reformat the entire repo.

File: libraries/lib-music-information-retrieval/MusicInformationRetrieval.h [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+    */
+   MusicInformation(const std::string& filename, double duration);
+
+   const std::string filename;
+   const double duration;
+
+   /*!
+    * @brief Tells whether the file contains music content.
+    */
+   operator bool() const;
```
[the remark this answers is not in the document]
Comment (saintmatthieu) [reply libraries/lib-music-information-retrieval/MusicInformationRetrieval.h:51]: Why not? I find it sensible and it reads great:
```
   MIR::MusicInformation musicInfo { fileName, newTrackDuration };
   if (!musicInfo)
      return;
```

File: libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.cpp [hunk 8]
```diff
@@ -0,0 +1,85 @@
...
+}
+
+void AudacityDontAskAgainMessageDialog::OnClose(wxCloseEvent& event)
+{
+   EndModal(wxID_NO);
+}
+
+void AudacityDontAskAgainMessageDialog::OnKeyDown(wxKeyEvent& event)
+{
+   if (event.GetKeyCode() == WXK_ESCAPE)
```
[the remark this answers is not in the document]
Comment (saintmatthieu) [reply libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.cpp:73]: Cool, thanks!

File: libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.cpp [hunk 9]
```diff
@@ -0,0 +1,85 @@
...
+      EndModal(wxID_NO);
+   else
+      event.Skip();
+}
+
+void AudacityDontAskAgainMessageDialog::OnButtonClick(wxCommandEvent& event)
+{
+   if (event.GetId() == wxID_NO)
```
[the remark this answers is not in the document]
Comment (saintmatthieu) [reply libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.cpp:81]: So that means that wxWidgets by default binds ESC with clicking a No button ?..
Anyway, thank you, it does work.

File: src/prefs/MusicInformationRetrievalPrefs.cpp (hunk 1 above)
Comment (saintmatthieu) [reply src/prefs/MusicInformationRetrievalPrefs.cpp:7]: We haven't discussed that with Design. I would say so, only then I wouldn't know if checking "Don't ask me again" should modify the value in that other dialog. @LWinterberg ?

File: src/ProjectFileManager.cpp (hunk 2 above)
Comment (saintmatthieu) [reply src/ProjectFileManager.cpp:1047]: VSCode does that for me on save. I could only stage and commit the changes that are not automatic, but we're better without those trailing whitespaces anyways.

File: src/ProjectFileManager.cpp (hunk 3 above)
Comment (saintmatthieu) [reply src/ProjectFileManager.cpp:65]: Obviously devs tried to manually keep these in order, and yet it was imperfect. Automatic re-ordering is painful for the reviewers when not done regularly, sorry about that, but then everyone could do it automatically and time would be spared.

File: libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (saintmatthieu) [reply libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.cpp:81]: ... pity that there isn't a `SetCloseButtonId(...)` ...

File: libraries/lib-wx-wrappers/SpinControl.cpp (hunk 5 above)
Comment (saintmatthieu) [reply libraries/lib-wx-wrappers/SpinControl.cpp:347]: I don't think this problem is related to the step size. The comment intends to give a comprehensive explanation, please let me know if there are unclarities.

**Review by vsverchinsky — COMMENTED** [review]
Approved, though would be nice to see this PR squashed into fewer amount of commits

**Review by vsverchinsky — DISMISSED** [review]

**Review by vsverchinsky — APPROVED** [review]
There are compilation issues that need to be addressed. 
PR has few commits that undo or redo something, would be nice if they are gone

**Comment by saintmatthieu** [comment]
Of course, I'll do a proper squash before merging. Thank you!

**Comment by dozzzzer** [comment]
### When importing a loop after another loop with a different tempo, stretching is applied

1. In a clean project, import a loop of 136 bpm
2. Click "Yes" in the appeared dialog
3. Observe: the project tempo is set to 136 bpm
4. Close the Track
5. Import a loop of 89 bpm
6. Click "Yes" in the appeared dialog
7. Observe: the project tempo is set to 89 bpm (which is correct), but the 50% stretching is applied to the clip

### When auto-stretching an imported loop, the algorithm doesn't seem to take into account its stretch ratio 

1. Set the project tempo to 90 bpm
2. Import a [4-bar loop of 128 bpm](https://www.dropbox.com/scl/fi/gksbt344qv8a5bkch6xc1/DK_Break_128_PL.wav?rlkey=1w0gj7ski886piotia8pgx28p&dl=0)
3. Click "No" in the Music Import dialog
4. Observe: the loop's speed is 70% (70.3125% to be precise)
5. With snapping enabled, shrink the loop to fit exactly 2 bars
6. Observe: the loop's speed is now 140.625%
7. Compare stretch ratios – 1.422 vs 1.406

Thus, it was supposed to go with the lesser one – 1.406 – which in this particular case would mean it should've **shrunk** the clip to 2 bars @ 90 bpm, not expanded it up to 4 bars @ 90 bpm.

### Undo resets the stretch ratio when Undo-ing

1. Set the project tempo to 120 bpm
2. Import a clip of 90 bpm
3. In the Music Import dialog, click No
4. Observe: the clip is shrunk (133% speed)
5. By holding Alt (Option), drag the edge of the clip and release to shrink or stretch the clip even more
6. Ctrl (Cmd) + Z

Actual result: back to 100% speed
Exp. result: 133% speed

### When importing a clip and auto-stretching it, the new speed value doesn't  immediately show up

1. Import a clip that has a tempo different from the project's one
2. Click No in the Music Import dialog in order to perform auto-stretching
3. Observe: no speed value at the top right corner of the clip's title bar
4. Hover over the clip's title bar
5. Observe: now the speed value pops up and the clip shrinks (expands) instantaneously


https://github.com/audacity/audacity/assets/70063970/f704a66a-f52d-47f6-a6a2-92251dc5d002

**Comment by saintmatthieu** [comment]
@dozzzzer the problems you reported should be fixed now.
I also simplified the regex and made it more conservative, too. Essentially, "BPM" (case-insensitive) must be found after the BPM value (will add something to the QA list). If this is not the case, I'm working on a DSP-based plan B anyway, which would give a second chance for these files to be tempo-detected.

**Comment by saintmatthieu** [comment]
> @saintmatthieu **Music Import** preference isn't working now in the updated branch. Regardless of the selected option in the Music Imports section, a musical file is imported as a regular audio file.

@dozzzzer I just tried it again, and it works for me. Could it be because the file you import doesn't have "BPM" in its title? https://github.com/audacity/audacity/pull/5570#issuecomment-1831475562

**Comment by saintmatthieu** [comment]
@LWinterberg just realizing that I've only been doing tempo detection when only one file is imported at a time.
I'd keep the multiple-file import in a follow-up ticket, because the desired behaviour isn't so simple.
If the user has set her preference to either auto-configure or do-nothing, then I suppose the behaviour would be almost as it is now, i.e., either do nothing or switch to B&M and auto-stretch, not touching the project tempo.
If the preference is on ask-me-each-time, though, the dialog might need be changed. Also, the preference's wording might need be generalized.

**Comment by saintmatthieu** [comment]
@dozzzzer follow-up ticket regarding multiple-file import: https://github.com/audacity/audacity/issues/5726

**Comment by dozzzzer** [comment]
@saintmatthieu 
When selecting "No" in the Music Import dialog, the imported clip gets auto-stretched. Ctrl-Z should then undo the import, rather than undoing the auto-stretching of the clip:


https://github.com/audacity/audacity/assets/70063970/a77bd0f9-8cb7-4e17-b00d-426d5176822b

**Comment by saintmatthieu** [comment]
@dozzzzer Just pushed a fix for both bullet points 1 and 2. As discussed and clarified, the tab-traversing item is actually only relevant to Windows ; I wasn't aware such functionality wasn't available on Mac.
Cheers!

**Comment by dozzzzer** [comment]
Tested

File: libraries/CMakeLists.txt [hunk 10]
```diff
@@ -60,6 +60,7 @@ set( LIBRARIES
    lib-menus
    lib-note-track
    lib-viewport
+   lib-music-information-retrieval
```
Comment (Paul-Licameli) [inline libraries/CMakeLists.txt:63]: I'm doing some after-the-fact review of this because I need the background to understand #5791.

I note the first commit in the sequence didn't build (test compilation failed)

File: libraries/lib-music-information-retrieval/MusicInformationRetrieval.cpp [hunk 11]
```diff
@@ -0,0 +1,120 @@
...
+}
+
+ProjectSyncInfo MusicInformation::GetProjectSyncInfo(
+   const std::optional<double>& projectTempo) const
+{
+   assert(*this);
+   if (!*this)
+      return { 0., 0. };
+
+   const auto error = *mBpm - bpmExpectedValue;
```
Comment (Paul-Licameli) [inline libraries/lib-music-information-retrieval/MusicInformationRetrieval.cpp:57]: Not yet used

File: src/CMakeLists.txt [hunk 12]
```diff
@@ -603,6 +603,8 @@ list( APPEND SOURCES
       prefs/MidiIOPrefs.h
       prefs/ModulePrefs.cpp
       prefs/ModulePrefs.h
+      prefs/MusicInformationRetrievalPrefs.cpp
+      prefs/MusicInformationRetrievalPrefs.h
```
Comment (Paul-Licameli) [inline src/CMakeLists.txt]: Second commit failed to build because this file did not exist yet

File: libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.h [hunk 13]
```diff
@@ -0,0 +1,22 @@
+#pragma once
```
Comment (Paul-Licameli) [inline libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.h:1]: No banner

File: libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.cpp [hunk 14]
```diff
@@ -0,0 +1,71 @@
...
+   // Add checkbox to the sizer so that it shows first
+   buttonSizer->Insert(0, checkBox, 0, wxALL | wxALIGN_CENTER, border);
+   mainSizer->Add(buttonSizer, 0, wxALL | wxALIGN_CENTER, border);
+
+   SetSizerAndFit(mainSizer);
+   // Manually implement wxCENTRE flag behavior
+   if (style | wxCENTRE != 0)
+      CentreOnParent();
+
+   SetEscapeId(wxID_NO);
```
Comment (Paul-Licameli) [inline libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.cpp:50]: All of this could have used ShuttleGui instead

File: src/prefs/MusicInformationRetrievalPrefs.cpp [hunk 15]
```diff
@@ -0,0 +1,9 @@
+#include "MusicInformationRetrievalPrefs.h"
```
Comment (Paul-Licameli) [inline src/prefs/MusicInformationRetrievalPrefs.cpp]: Banners please for this and the .h file

File: src/prefs/MusicInformationRetrievalPrefs.cpp [hunk 16]
```diff
@@ -0,0 +1,9 @@
...
+
+ChoiceSetting UseMirResultToConfigureProject {
+   wxT("/GUI/UseMirResultToConfigureProject"),
+   { ByColumns,
+     { {}, {}, {} },
```
Comment (Paul-Licameli) [inline src/prefs/MusicInformationRetrievalPrefs.cpp]: This associated empty user-visible strings with the identifiers.  That's wrong.  But what happened in later commits? ...

File: libraries/lib-wave-track/WaveClip.h [hunk 17]
```diff
@@ -160,11 +160,13 @@ class WAVE_TRACK_API WaveClip final :
 
    // Set rate without resampling. This will change the length of the clip
    void SetRate(int rate);
+   void SetRawAudioTempo(double tempo);
 
    //! Stretches from left to the absolute time (if in expected range)
    void StretchLeftTo(double to);
    //! Sets from the right to the absolute time (if in expected range)
    void StretchRightTo(double to);
+   void StretchBy(double ratio);
```
Comment (Paul-Licameli) [inline libraries/lib-wave-track/WaveClip.h:169]: I really don't like it that lib-wave-track and lib-track have all this mention of stretches and tempos, which are extraneous to what should be lesser and more easily understood class responsibilities.

It's not for you to clean up now, but along with wave clip refactoring, I want to figure out dependency inversion between lib-wave-track and lib-stretching-sequence.

File: libraries/lib-wave-track/WaveTrack.cpp [hunk 18]
```diff
@@ -262,6 +262,12 @@ void WaveTrack::Interval::StretchRightTo(double t)
       GetClip(channel)->StretchRightTo(t);
 }
 
+void WaveTrack::Interval::StretchBy(double ratio)
+{
+   for (unsigned channel = 0; channel < NChannels(); ++channel)
+      GetClip(channel)->StretchBy(ratio);
```
Comment (Paul-Licameli) [inline libraries/lib-wave-track/WaveTrack.cpp:274]: This might use `ForEachClip`

File: src/ProjectFileManager.cpp [hunk 19]
```diff
@@ -16,49 +16,58 @@ Paul Licameli split from AudacityProject.cpp
 #include <wx/evtloop.h>
 #endif
 
-#include <wx/frame.h>
-#include <wx/log.h>
+#include "AdornedRulerPanel.h"
+#include "AudacityDontAskAgainMessageDialog.h"
```
Comment (Paul-Licameli) [inline src/ProjectFileManager.cpp:20]: I really dislike this added dependency

File: src/ProjectFileManager.cpp [hunk 20]
```diff
@@ -16,49 +16,58 @@ Paul Licameli split from AudacityProject.cpp
...
+#include "RealtimeEffectList.h"
 #include "SelectFile.h"
 #include "SelectUtilities.h"
 #include "SelectionState.h"
 #include "Tags.h"
 #include "TempDirectory.h"
+#include "TimeDisplayMode.h"
 #include "TrackFocus.h"
 #include "TrackPanel.h"
+#include "TrackPanelAx.h"
```
Comment (Paul-Licameli) [inline src/ProjectFileManager.cpp:52]: Unnecessary

File: src/ProjectFileManager.cpp [hunk 21]
```diff
@@ -16,49 +16,58 @@ Paul Licameli split from AudacityProject.cpp
...
-#include "wxFileNameWrapper.h"
-#include "Export.h"
-#include "Import.h"
-#include "ImportProgressListener.h"
-#include "ImportPlugin.h"
+#include "XMLFileReader.h"
 #include "import/ImportStreamDialog.h"
-#include "AudacityMessageBox.h"
+#include "prefs/MusicInformationRetrievalPrefs.h"
+#include "toolbars/SelectionBar.h"
```
Comment (Paul-Licameli) [inline src/ProjectFileManager.cpp:59]: unnecessary

File: src/ProjectFileManager.cpp [hunk 22]
```diff
@@ -1286,15 +1295,122 @@ class ImportProgress final
...
+                UserResponseToMirPrompt::PreferenceYes :
+                UserResponseToMirPrompt::No;
+}
+}
+
+void ReactOnMusicFileImport(
+   const std::string& fileName, const TrackHolders& newTracks,
+   AudacityProject& project)
+{
+   const auto waveTracks = newTracks[0]->Any<WaveTrack>();
```
Comment (Paul-Licameli) [inline src/ProjectFileManager.cpp:1348]: This assumes `newTracks` is not empty and no other subscript it used.

Maybe the argument should be `const Tracklist &`

File: src/ProjectFileManager.cpp [hunk 23]
```diff
@@ -1286,15 +1295,122 @@ class ImportProgress final
...
+   const auto projectTempo = ProjectTimeSignature::Get(project).GetTempo();
+   const auto syncInfo = musicInfo.GetProjectSyncInfo(projectTempo);
+
+   const auto isFirstWaveTrack =
+      TrackList::Get(project).Any<WaveTrack>().empty();
+   const auto isBeatsAndMeasures =
+      TimeDisplayModePreference.ReadEnum() == TimeDisplayMode::BeatsAndMeasures;
+
+   const auto clips = newTrack.Intervals();
+   assert(clips.size() == 1);
```
Comment (Paul-Licameli) [inline src/ProjectFileManager.cpp:1373]: What proves the assertion?

You really rely on the weaker condition `clips.size() > 0`

File: src/ProjectFileManager.cpp [hunk 24]
```diff
@@ -1286,15 +1295,122 @@ class ImportProgress final
...
+   const auto clip = *clips.begin();
+
+   if (!isFirstWaveTrack && !isBeatsAndMeasures)
+   {
+      // Do nothing.
+   }
+   else if (!isFirstWaveTrack && isBeatsAndMeasures)
+   {
+      // B&B view and not first track -> silently stretch clip.
```
Comment (Paul-Licameli) [inline src/ProjectFileManager.cpp]: You mean "B&M" ?

File: src/prefs/ImportExportPrefs.cpp [hunk 25]
```diff
@@ -109,14 +128,40 @@ void ImportExportPrefs::PopulateOrExchange(ShuttleGui & S)
...
+         {
+            S.TieRadioButton();
+            S.TieRadioButton();
+            S.TieRadioButton();
+         }
+         S.EndRadioButtonGroup();
+      }
+      S.EndPanel();
+   }
+   S.EndStatic();
```
Comment (Paul-Licameli) [inline src/prefs/ImportExportPrefs.cpp:155]: OK so this commit corrects the previous, using ShuttleGui.

I wonder if a `PopulatorItem` could be used and other tricks to make the music information retrieval a non-intrusively defined module.  Also breaking the dependencies added in ProjectFileManager.cpp.

File: libraries/lib-wave-track/WaveClip.cpp [hunk 26]
```diff
@@ -1343,6 +1343,15 @@ void WaveClip::TrimRight(double deltaTime)
    SetTrimRight(mTrimRight + deltaTime);
 }
 
+void WaveClip::TrimQuarternotesFromRight(double quarters)
```
Comment (Paul-Licameli) [inline libraries/lib-wave-track/WaveClip.cpp:1346]: Ideally WaveTrack and WaveClip should not mention quarter notes!

File: src/ProjectFileManager.cpp (hunk 23 above)
Comment (saintmatthieu) [reply src/ProjectFileManager.cpp:1373]: From the context: surely importing one file results in one clip, and importing more than one files, in more than one tracks each with one clip. This could be a post-condition of `Importer::Import` (currently not stated).

File: src/prefs/ImportExportPrefs.cpp (hunk 25 above)
Comment (saintmatthieu) [reply src/prefs/ImportExportPrefs.cpp:155]: ?

**Comment by saintmatthieu** [comment]
@Paul-Licameli I'm addressing your comments on #5791.
