### PR TITLE
No room hotfix

### LINKED ISSUE #5268: Crash when opening up Mixer
### Steps to reproduce

1. Download [the project](https://www.dropbox.com/scl/fi/amkwq2zyy3k81kpzmti80/Everything_App_Project.aup3?rlkey=vwnx186uusch34c8xwkp964rp&dl=0)
2. Open the project in Audacity and dismiss the missing plugins warning
3. Click Play
4. Open up Mixer (View > Mixer)
5. Wait a few moments until the play head hits bar 33

### Expected behavior

No crash

### Actual behavior

A crash

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS, Windows

### LINKED ISSUE #5279: Crash applying effect to overlapping zero-width clip
### Bug description

I have about a  piece of audio that I'm working with, and all of a sudden whenever I try to normalize sections of it, it completely crashes. This is out of nowhere.  I've been using audacity for years!  Paul Licameli , any thoughts?

### Steps to reproduce

1. Load the file in Audacity: https://www.dropbox.com/scl/fi/19sdon2c40gzp1zo3lz4y/Joe-Essay-Audacity-Failure.aup3?rlkey=5pmwhd0to43cw5r224rfz7c10&dl=0
2. Make a selection of audio
3. Attempt to normalize it

### Expected behavior

It should normalize the audio appropriately

### Actual behavior

Crash

### Audacity Version

Audacity Version 3.2.4

### Operating system

macOS

### PR DESCRIPTION
**Pull request by vsverchinsky**
Resolves: #5292

Another attempt to fix "no room" error

- [ ] I signed [CLA](https://www.audacityteam.org/cla/)
- [ ] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [ ] Each commit's message describes its purpose and effects
- [ ] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:
- [x] Fixes #5268
- [x] Fixes #5279

### CODE REVIEW

File: libraries/lib-wave-track/WaveTrack.cpp [hunk 1]
```diff
@@ -2725,7 +2738,7 @@ XMLTagHandler *WaveTrack::HandleXMLChild(const std::string_view& tag)
       auto clip = std::make_shared<WaveClip>(1,
          mpFactory, mLegacyFormat, mLegacyRate, GetWaveColorIndex());
       const auto xmlHandler = clip.get();
-      InsertClip(std::move(clip));
+      mClips.push_back(std::move(clip));
```
Comment (saintmatthieu) [inline libraries/lib-wave-track/WaveTrack.cpp:2741]: I'd prefer to keep exclusively using `InsertClip` for adding clips. Here you bypass it because it's a case where it's okay that the clip is empty, but other coders later may not realize this and think it's okay to just push a new clip.
Would you please consider adding a boolean argument to `InsertClip` which defaults to rejecting empty clips ?

**Review by saintmatthieu — APPROVED** [review]

File: libraries/lib-wave-track/WaveTrack.cpp (hunk 1 above)
Comment (vsverchinsky) [reply libraries/lib-wave-track/WaveTrack.cpp:2741]: Sure

**Comment by chinakov** [comment]
Tested - all check-list items and the original issue (Not enough room for pasting) have been fixed.
