### PR TITLE
[10510] Factory-reset: close cloud DB and unify flow                                                                                                                                                                        

### LINKED ISSUE #9677: Revert to factory settings – copy update
The copy of the 'Revert to factory settings' dialog relates to MuseScore. 
This needs to be updated.

Image

### LINKED ISSUE #10510: Revert to factory setting crash
@luapmartin 

On MacOS, after you launch the build and dismiss all dialogs, selecting "Help > Revert to factory settings" won't restart Audacity. This is a regression against master.

_Originally posted by @dozzzzer in https://github.com/audacity/audacity/issues/10481#issuecomment-4023149759_

### PR DESCRIPTION
**Pull request by luapmartin**
Resolves: 
Revert to factory setting crash https://github.com/audacity/audacity/issues/10510
copy update https://github.com/audacity/audacity/issues/9677

  - Unify factory-reset entry points via FactoryResetMode; close CloudProjectsDatabase before wiping config                                                                                                                   
  - Multi-window restart-confirmation handling; cancel is default                                                                                                                                                             
  - Add single- and multi-window action-controller tests; drop unused -R CLI flag

this PR replaces https://github.com/audacity/audacity/pull/10518

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA:

- [ ] Testflow test cases have been run

### CODE REVIEW

File: src/appshell/internal/appshellconfiguration.cpp [hunk 1]
```diff
@@ -21,11 +21,14 @@
  */
 #include "appshellconfiguration.h"
 
+#include <QFileInfo>
```
Comment (kryksyh) [inline src/appshell/internal/appshellconfiguration.cpp]: are those headers used?

File: src/stubs/au3cloud/au3audiocomservicestub.cpp [hunk 2]
```diff
@@ -52,3 +52,7 @@ muse::ProgressPtr Au3AudioComServiceStub::resumeProjectSync(au::project::IAudaci
 {
     return nullptr;
 }
+
+void Au3AudioComServiceStub::deinit()
```
Comment (kryksyh) [inline src/stubs/au3cloud/au3audiocomservicestub.cpp:56]: is it required?

**Review by kryksyh — APPROVED** [review]

**Review by kryksyh — APPROVED** [review]

File: src/appshell/internal/appshellconfiguration.cpp (hunk 1 above)
Comment (luapmartin) [reply src/appshell/internal/appshellconfiguration.cpp]: jedi hands weaving
