### PR TITLE
EffectOutputTracks copies clip IDs when duplicating

### LINKED ISSUE #7799: A project cannot be opened once an effect has been applied to its audio
### Bug description

_No response_

### Steps to reproduce

1. Open a project created in AU3 containing audio data
2. Make a selection and apply Reverb to it
3. Ctrl + W
4. "Don't save"
5. Try to reopen the project

### Expected behavior

The project can be reopened.

### Actual behavior

The project cannot be reopened. Clicking the project thumbnail and selecting the project via Ctrl + O don't do anything.

### Audacity Version

Audacity 4 alpha

### Operating system

Other

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #7799

Addresses the case of EffectOutputTracks, where, when duplicating the original track, the clip IDs should match the original.
Problem discussed internally [here](https://mu--se.slack.com/archives/C06RX437GJV/p1731925325477879).

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: au3/libraries/lib-effects/EffectOutputTracks.cpp [hunk 1]
```diff
@@ -41,6 +42,19 @@ EffectOutputTracks::EffectOutputTracks(
 
    for (auto aTrack : trackRange) {
       auto pTrack = aTrack->Duplicate();
+      if (auto aWaveTrack = dynamic_cast<WaveTrack*>(aTrack))
```
Comment (kryksyh) [inline au3/libraries/lib-effects/EffectOutputTracks.cpp:45]: this makes me think that there are other places where duplicated track should also duplicate clip ids. I'm not opposed to have this merged, but what do you think about introduce this as an optional behavior to `Duplicate`?

Comment (saintmatthieu) [reply au3/libraries/lib-effects/EffectOutputTracks.cpp:45]: You find that this PR solves this ID problem only in the context of effects but that preserving clip IDs might be desired in other situations, too?
Where `Duplicate()` is called (I changed the name to something silly and fixed compilation to make sure I haven't missed any):
* `EffectOutputTracks`: IDs must be copied
* `ProjectCloudExtension::OnSyncStarted()` : I think it doesn't matter?
* `PendingTracks`: outdated ;)
* Undo/Redo: at the moment new IDs are given, and it seems to work (I don't know why)
* In `WaveTrack::ClearAndPaste`: new IDs are given, which is correct
* `Au3Interaction::duplicateTracks`: new IDs are given, correct.

So for now at least it would seem that we're good?

Yes, in the future a situation may arise where we need to duplicate with equal IDs. I'm not sure how to change the `Duplicate` API, though, as this is a `Track` API, and other track types may not have clips (e.g. label tracks).

Comment (kryksyh) [reply au3/libraries/lib-effects/EffectOutputTracks.cpp:45]: > Undo/Redo: at the moment new IDs are given, and it seems to work (I don't know why)

Now I wonder why applying an effect breaks the project while undo doesn't. If I understand correctly, undo does the same thing as an effect does:  it creates a new track and replaces the original track, including all of its clips.

**Review by kryksyh — APPROVED** [review]

File: au3/libraries/lib-effects/EffectOutputTracks.cpp (hunk 1 above)
Comment (saintmatthieu) [reply au3/libraries/lib-effects/EffectOutputTracks.cpp:45]: All things considered, I'll move this to QA already: having this merged would unblock the other ticket I'm working on.

Comment (saintmatthieu) [reply au3/libraries/lib-effects/EffectOutputTracks.cpp:45]: @kryksyh https://github.com/audacity/audacity/pull/7880
