### PR TITLE
7843 prevent editing during recording

### LINKED ISSUE #7843: Dissallow the User to interact with clip in Recording
### Bug description

If the User starts to record a new audio clip, the User is allowed to change the position of the clip. This can generate a crash, or loss of audio clips if the recorded audio clip is moved 'onto' those clips. 

https://github.com/user-attachments/assets/b01412d4-d420-42bd-9b40-5d79cac6881b

### Steps to reproduce

1. Launch Audacity
2. Create a Mono or Stereo track
3. Start recording into the track
4. Try to move the recorded clip
5. Observe result

### Expected behavior

The User should not be allowed to change position of any recorded clip. 

### Actual behavior

The User should is allowed to change position of any recorded clip. 

### Audacity Version

Audacity 4 alpha

### Operating system

Windows

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #7843

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: src/trackedit/internal/trackeditactionscontroller.cpp [hunk 1]
```diff
@@ -49,6 +49,20 @@ static const ActionCode REDO("redo");
...
+    CUT_CODE,
+    // etc.
+};
+
+namespace {
+bool isDisallowedDuringRecording(const ActionCode& actionCode)
+{
+    return std::find(actionsDisabledDuringRecording.begin(), actionsDisabledDuringRecording.end(),
+                     actionCode) != actionsDisabledDuringRecording.end();
+}
```
Comment (igorkorsukov) [inline src/trackedit/internal/trackeditactionscontroller.cpp:63]: for information only
```
#include "global/containers.h"

muse::contains(actionsDisabledDuringRecording, actionCode);
```

File: src/trackedit/internal/trackeditactionscontroller.cpp [hunk 2]
```diff
@@ -753,6 +773,8 @@ bool TrackeditActionsController::canReceiveAction(const ActionCode& actionCode)
 {
     if (globalContext()->currentProject() == nullptr) {
         return false;
+    } else if (recordController()->isRecording() && isDisallowedDuringRecording(actionCode)) {
```
Comment (igorkorsukov) [inline src/trackedit/internal/trackeditactionscontroller.cpp:776]: just a suggestion, maybe we should add `isRecording` to the global context?  
It might just be a little more convenient, fewer dependencies, for example less mocking and configuring when trying to write a unit test

Comment (saintmatthieu) [reply src/trackedit/internal/trackeditactionscontroller.cpp:776]: Makes sense.

**Review by igorkorsukov — APPROVED** [review]
