### PR TITLE
Fix shifting clip to left of 0 mark breaking spectrum display

### LINKED ISSUE #4882: Shifting clip to left of 0 mark breaks spectrum display
### Bug description

_No response_

### Steps to reproduce

1. Have a track with audio.
2. Switch to spectrum display.
3. Move clip left to the zero mark.

### Expected behavior

Spectrum display works.

### Actual behavior

Spectrum display turns black.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Was introduced by recent caching-refactoring PR https://github.com/audacity/audacity/pull/4771

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #4882

Fix in recent caching refactoring code, where the calculation of number of samples for readout wrongly compared absolute with relative times.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

File: libraries/lib-wave-track/WaveTrack.cpp [hunk 1]
```diff
@@ -2268,21 +2268,21 @@ WaveTrack::GetOneSampleView(sampleCount start, size_t length) const
...
       const auto clipT0 = t0 - clipStartTime;
       const auto clipS0 = TimeToLongSamples(clipT0);
-      // By substitution,
-      //    (len - length) / rate = t0 - clipT0,
-      // and since
-      //    t0 - clipT0 <= 0,
-      // then `length >= len`. `as_size_t` won't narrow.
-      const auto len = TimeToLongSamples(t1 - clipT0).as_size_t();
+      const auto len =
+          std::min((clip->GetPlaySamplesCount() - clipS0).as_size_t(), length);
```
Comment (Paul-Licameli) [inline libraries/lib-wave-track/WaveTrack.cpp:2278]: You might use `limitSampleBufferSize`

Comment (Paul-Licameli) [reply libraries/lib-wave-track/WaveTrack.cpp:2278]: In fact that would be more correct.  The narrowing to size_t here might sometimes make a small number.  Better to widen `length` before taking `min`

**Review by Paul-Licameli — CHANGES_REQUESTED** [review]
Make the suggested change to avoid narrowing.

**Review by Paul-Licameli — APPROVED** [review]
